### ISSUE TITLE
how to remove %HESITATION from transcription using the sdk?

### ISSUE THREAD

**Issue by masaldana2** [watson-developer-cloud/swift-sdk#1008]
i know you can use the 'keywords' parameter in the recognize call somehow, but I just keep getting errors.
how to use it properly so i can stop getting '%HESITATION'? 

Thank you

**Comment by repjarms** [comment]
@masaldana2 I do not believe there is a way for you to specify with the SpeechToText service that you do not want to receive `%HESISTATION` markers in the transcript.

According to the [Speech to Text documentation](https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-basic-response#hesitation), the recommended way to remove this is to filter it manually from the transcript.

In Swift, you could do that with something like this:

```swift
let filteredTranscript = transcript.replacingOccurrences(of: "%HESISTATION", with: "")
```
