### ISSUE TITLE
Unable to build scheme "SpeechToTextV1" using Carthage

### ISSUE THREAD

**Issue by xezero** [watson-developer-cloud/swift-sdk#1010]
The command I'm using is: 
`carthage build swift-sdk --platform iOS --no-use-binaries --cache-builds`

The Swift version I'm using is 5.1

*** Building scheme "SpeechToTextV1" in WatsonDeveloperCloud.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun dwarfdump --uuid /Users/kevin/Library/Caches/org.carthage.CarthageKit/DerivedData/11.3.1_11C504/swift-sdk/v3.3.0/Build/Intermediates.noindex/ArchiveIntermediates/SpeechToTextV1/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SpeechToTextV1.framework/SpeechToTextV1

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/mq/c7bgc49s5f5dwhsyl56rt0900000gn/T/carthage-xcodebuild.KKgTMt.log

[carthage-xcodebuild.KKgTMt.log](https://github.com/watson-developer-cloud/swift-sdk/files/4352889/carthage-xcodebuild.KKgTMt.log)

**Comment by repjarms** [comment]
@xezero thanks for filing this. I'll take a look at trying to replicate this.

**Comment by xezero** [comment]
Thank you! It also seems like some of the other schemas don’t finish building with Carthage either, like TextToSpeech.

**Comment by repjarms** [comment]
@xezero what version of Carthage are you using?

**Comment by xezero** [comment]
@repjarms 0.34.0

**Comment by xezero** [comment]
So it looks like the x86 framework is what’s failing. The frameworks for arm architectures build fine.

**Comment by xezero** [comment]
@repjarms Would it be possible to add SPM support for SpeechToTextV1 (the Package.swift seems to be missing a few targets like this one)?

That would indirectly resolve this issue for me as well if I can simply compile via SPM :)

**Comment by mediumTaj** [comment]
Is this still an issue?
