### ISSUE TITLE
Import as Swift Package Compile Error in IBMSwiftCoreSDK

### ISSUE THREAD

**Issue by benjaminbruch** [watson-developer-cloud/swift-sdk#1015]
**Overview**

**Expected behavior**
Would like to add repository as a SwiftPackage to a XcodeProject. **Not** as an dependency in another SwiftPackage.

**Actual behavior**
Compile-Error see screenshots below.

**How to reproduce**

1. Create new iOS-Xcode-Project
2. Goto "File -> Swift-Packages -> Add package dependency"
3. Enter URL: https://github.com/watson-developer-cloud/swift-sdk
4. Confirm version
5. After package is downloaded try to build/compile project

**Screenshots**
![Bildschirmfoto 2020-05-12 um 10 08 51](https://user-images.githubusercontent.com/19404588/81658964-8d20b880-9439-11ea-9b6a-fd2e1076bde6.png)

![Bildschirmfoto 2020-05-12 um 10 09 19](https://user-images.githubusercontent.com/19404588/81659000-9742b700-9439-11ea-881e-74acb63df751.png)

**SDK Version**
Latest - 3.4.0

**Additional information:**
- Xcode: Version 11.4 (11E146)
- Swift: 5.2

**Additional context**
I cloned https://github.com/IBM/swift-sdk-core as a SwiftPackage and tried to compile it, but got the same error.
When downloaded as archive with projects files there are no build errors.
Maybe there is some problem with package structure.

Thanks in advance

**Comment by benjaminbruch** [comment]
I made a pull request in https://github.com/IBM/swift-sdk-core to fix this error.

**Comment by pearl7721User1** [comment]
still having the same issue.
