### ISSUE TITLE
Catalyst support

### ISSUE THREAD

**Issue by masaldana2** [watson-developer-cloud/swift-sdk#1016]
I get the error when building. I'm using speech to text

> ld: building for Mac Catalyst, but linking in object file built for iOS Simulator, for architecture x86_64

Catalyst is the future for mac and should be supported. : )

**Comment by germanattanasio** [comment]
If you know what the future is like tell me the lottery winning numbers. We can go 50% 50% 😛

**Comment by masaldana2** [comment]
lol any workaround i can try for speech to text only?
