### ISSUE TITLE
Swift Package Manager Error

### ISSUE THREAD

**Issue by juliobailon** [watson-developer-cloud/swift-sdk#1036]
**Overview**
When using Swift Package Manager I am getting this error:

/swift-sdk/Source/AssistantV1/Assistant.swift:90:19: Cannot find 'InsecureConnection' in scope

**Expected behavior**
Proper compilation of the WatsonDeveloperCloud Swift Package

**Actual behavior**
Error: Cannot find 'InsecureConnection' in scope

**How to reproduce**
In Xcode 12 just add the Swift Package in https://github.com/watson-developer-cloud/swift-sdk version 3.6.0

**SDK Version**
Xcode 12.2

**Comment by misolubarda** [comment]
Any news about this? :)

**Comment by repjarms** [comment]
@misolubarda we are almost there! We have a PR open https://github.com/watson-developer-cloud/swift-sdk/pull/1047 which will kick off a new version that adds Swift Package Manager support and resolves some issues with Carthage and Cocoapods on XCode 12.

I expect the release to go out in the next few days.

**Comment by repjarms** [comment]
@misolubarda @juliobailon Version `4.1.0` has been released and fixes the issues with SPM compiling. I'm going to close this now but feel free to re-open or post another issue if something comes up!
