### ISSUE TITLE
4.x Migration Guide

### ISSUE THREAD

**Issue by jminutaglio** [watson-developer-cloud/swift-sdk#1049]
Changes from 3.6 to 4.1 result in non-compiling code - even the IBM sample projects no longer compile.  Specifically with Watson Assistant v2.  IBM documentation links also still reference 3.x.

Will there be a 4.x migration guide and/or when will sample projects and general API documentation be updated?

TY!

**Comment by apaparazzi0329** [comment]
As is with any major release breaking changes are expected. You can find the v4 migration guide [here](https://github.com/watson-developer-cloud/swift-sdk/blob/master/MIGRATION-V4.md). As for the sample projects, we are currently updating them.
