### ISSUE TITLE
Configure code coverage to ignore tests

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#156]
There really isn't a need to test the tests. Is it possible to ignore files with our code coverage tool?

@vherrin 
@rfdickerson

**Comment by glennrfisher** [comment]
The changes in #281 did not properly ignore the tests. I'm not sure why they continued to show up in codecov. I'm going to table this for now and come back to it in the future.

**Comment by mkistler** [comment]
Closing as tests no longer show up in latest code coverage reportsL

https://codecov.io/gh/watson-developer-cloud/swift-sdk/tree/2656fb227b54bb9a36f864648db92e683afde002
