### ISSUE TITLE
Check for memory leaks caused by strong reference cycles

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#213]
Many strong reference cycles are caused by using `self` in a closure. Let's check our code for any closures that refer to `self` and ensure that they do not cause a strong reference cycle.

If they do, then we should use `weak` if the class is optional and `unowned` when it isn't.

**Comment by repjarms** [comment]
Closing this as some time has passed and we are several majors ahead now.
