### ISSUE TITLE
Explore Playdown

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#274]
[Playdown](https://github.com/matthewpalmer/Playdown) is a tool that can convert a Swift file to Markdown. This might be really helpful for generating documentation, since we can verify that the Swift code within the documentation builds and runs successfully.

**Comment by glennrfisher** [comment]
Let's tackle this when we create a separate repository for examples. We can migrate the current readme to a playground file with markdown comments. The playground helps us ensure that the code is up-to-date and builds correctly. Then we can make updates to the playground and run Playdown to convert it to markdown for the readme.

**Comment by mkistler** [comment]
We've settled on Jazzy as our documentation generation tool.
