### ISSUE TITLE
Submit request to update BlueMix security

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#30]
BlueMix does not support the standards required by Apple's "App Transport Security" in iOS 9. As a result, we need to modify the App Transport Security for each example application. Instead, we should submit a request to update BlueMix's security standards so that our SDK's clients do not have to make exceptions or disable App Transport Security.

For more information on App Transport Security see this [blog post](http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/).

Here is the error that was produced by the `SpeechTranscriptionDemo` application when App Transport Security was not disabled or modified:

``` swift
2015-09-13 09:42:03.886 SpeechTranscriptionDemo[29039:1519370] CFNetwork SSLHandshake failed (-9824)
2015-09-13 09:42:03.887 SpeechTranscriptionDemo[29039:1519370] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)
```

**Comment by johnmci** [comment]
Yesterday we had added a NSExceptionMinimumTLSVersion TLSv1.0 to allow access to gateway.watsonplatform.net. But today I see it suddenly supports TLS1.2 so we removed that parm.

**Comment by glennrfisher** [comment]
Excellent! Thanks @johnmci. That's really great to know.

We'll run some tests just to verify that we see the same behavior then look into removing the App Transport Security exceptions from the quick start documentation.

**Comment by johnmci** [comment]
Ok the site graded a b- yesterday on ssllabs but this morning it changed to a A-  missing is perfect forward security so you need an exception for that

**Comment by glennrfisher** [comment]
Ah, okay.

@kweinmeister, @vherrin: Do you know how to get in touch with the Watson Labs team to note the requirement for perfect forward secrecy?

**Comment by LinZhao1** [comment]
Hi @glennrfisher 

My team still experience this problem. My team is using AlchemyAPI. Below are the log I had if enable ATS. Please let me know if you find a way to contact Watson Labs Team, want to know what the process they have for this issue.

`2016-04-06 13:55:57.219 Healthy-Corner[11542:201402] CFNetwork SSLHandshake failed (-9824)
2016-04-06 13:55:57.220 Healthy-Corner[11542:201402] NSURLSession/NSURLConnection HTTP load failed`

Thanks 

Lin Zhao

**Comment by glennrfisher** [comment]
Hi @LinZhao1.

The problem you are experiencing with BlueMix security requires you to add the watsonplatform.net domain as an exception for App Transport Security. Did you complete step 11 of the [Quickstart Guide](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Quickstart.md)? If so then the security requirements, while inconvenient, should not affect the actual operation of your application.

We've reached out to a number of folks who are aware of and working to enhance the security standards used by BlueMix. I hope we will no longer need to add an exception to App Transport Security in the near future. But for now, be sure to follow the instructions laid out in the Quickstart Guide to bypass the App Transport Security requirements for the Watson platform.

**Comment by LinZhao1** [comment]
Thanks Glenn
 
Your reply is really helpful.
 
Best Regards  
                                                                        Lin Zhao                         Watson Health Innovations Mobile                                                 IBM Technology Campus, Building 3                        Damastown Industrial Estate                        Dublin 15, Ireland                                                                                                                                                                                                                                                                                                              Mobile:   353876767808                                                E-mail:    LZhao@ie.ibm.com                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                IBM Ireland Product Distribution Limited Registered in Ireland with no.: 92815 Registered Office: IBM House, Shelbourne Road, Ballsbridge, Dublin 4, Ireland                                                                                                                                                                                                
 
 
----- Original message -----From: "Glenn R. Fisher" <notifications@github.com>To: watson-developer-cloud/ios-sdk <ios-sdk@noreply.github.com>Cc: Lin Zhao/Ireland/IBM@IBMIESubject: Re: [watson-developer-cloud/ios-sdk] Submit request to update BlueMix security (#30)Date: Wed, Apr 6, 2016 4:43 PM 
Hi @LinZhao1.
The problem you are experiencing with BlueMix security requires you to add the watsonplatform.net domain as an exception for App Transport Security. Did you complete step 11 of the Quickstart Guide? If so then the security requirements, while inconvenient, should not affect the actual operation of your application.
We've reached out to a number of folks who are aware of and working to enhance the security standards used by BlueMix. I hope we will no longer need to add an exception to App Transport Security in the near future. But for now, be sure to follow the instructions laid out in the Quickstart Guide to bypass the App Transport Security requirements for the Watson platform.
—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by miltonleung** [comment]
Hi @glennrfisher and team,

Are there any updates on request filed? Thanks!

**Comment by glennrfisher** [comment]
Hi @miltonleung! Thanks for following up on this issue.

It seems like the Bluemix team has upgraded their security standards—I've been working on a tutorial app and have not needed to enter an exception for the Bluemix domain.

I'm away from the office this week, but can write a test next week to confirm. If that's the case, then we can remove some of the instructions in the readme and quick start guide around the App Transport Security exceptions.

**Comment by miltonleung** [comment]
That is great news! Thanks so much for the prompt response.

**Comment by glennrfisher** [comment]
Thanks again, @miltonleung! Just confirmed that the app transport security exception is no longer needed. Commit 356bbeda15864bac48a5c6aaa2486a8f2dcd83fd removes those steps from the documentation. Appreciate your follow-up!
