### ISSUE TITLE
Improve AlchemyLanguage API

### ISSUE THREAD

**Issue by thomaspaulmann** [watson-developer-cloud/swift-sdk#319]
I've seen that the method parameters of the alchemy language are weird for different document types. Here is an example:

```
public func getAuthorsHtml(
  html: NSURL,
  url: String? = nil,
  failure: (NSError -> Void)? = nil,
  success: DocumentAuthors -> Void) { }

public func getAuthorsURL(
  url: String,
  failure: (NSError -> Void)? = nil,
  success: DocumentAuthors -> Void) { }
```

Is it supposed to be so? Especially that the paramter `url` is of the type `String`? I've dived a little bit into the code behind the scenes and it looks that it doesn't matter if it's `NSURL` or `String`.
This looks like an inconsistent API. Furthermore there are more inconsistency if you look to other methods like the API for emotion extraction:

```
public func getEmotionURL(
  url: NSURL,
  failure: (NSError -> Void)? = nil,
  success: DocumentEmotion -> Void) { }

public func getEmotionHtml(
  html: String,
  url: String? = nil,
  failure: (NSError -> Void)? = nil,
  success: DocumentEmotion -> Void) { }

public func getEmotionText(
  text: String,
  failure: (NSError -> Void)? = nil,
  success: DocumentEmotion -> Void) { }
```

What about synchronising all this methods in a similar way. I would also make it a little _swiftier_. My suggestion would be something like this:

```
public func getEmotion(
  forUrl url: NSURL,
  failure: (NSError -> Void)? = nil,
  success: DocumentEmotion -> Void) { }

public func getEmotion(
  forHtml html: String,
  failure: (NSError -> Void)? = nil,
  success: DocumentEmotion -> Void) { }

public func getEmotion(
  forText text: String,
  failure: (NSError -> Void)? = nil,
  success: DocumentEmotion -> Void) { }
```

What do you think about the solution? Furthermore we can extend this to the whole Alchemy Language API. I guess this gives more transparency to the developer. 

I would love to help with the refactoring and would contribute it.

**Comment by Hsaylor** [comment]
Thanks for the feedback! I agree that synchronizing the method names is a great change (honestly it should've been caught in code review, oops). Feel free to submit a pull request for it.

As for the `String` vs `NSURL` issue we're currently undecided on the best approach. We're a little timid on changing the url related calls to take `NSURL` because it doesn't necessarily have to point to a web hosted document, which is required for the service. Obviously neither does a string, but the use of `NSURL` may incorrectly imply safety that doesn't exist.

**Comment by vherrin** [comment]
This is a great suggestion especially since this follows some changes in the base swift 3 language to push some of the selection implementation into the param list

**Comment by thomaspaulmann** [comment]
@hsaylor Ok, makes sense. In the first step I will only synchronise the method names and parameters. In the next step we can have a look to the types of the parameters. 

@vherrin Thanks for the kind words, appreciate it. What are the plans for monday when Swift 3 will be released. Creating a separater branch and support swift 2 and 3?

**Comment by thomaspaulmann** [comment]
I will also look into other APIs and check if there are same issues.

**Comment by thomaspaulmann** [comment]
@Hsaylor Ok, now I see that you want to load a text document. What about a pure text from an input field? Probably that is also an use case. So maybe we should extend the functionality and add another method:
```
public func getEmotion(
  forText text: String,
  failure: (NSError -> Void)? = nil,
  success: DocumentEmotion -> Void) { }

public func getEmotion(
  forTextDocument text: NSURL,
  failure: (NSError -> Void)? = nil,
  success: DocumentEmotion -> Void) { }
```
This solution gives the developer the freedom of choice. If it's ok for you, I would integrate this as well.

**Comment by Hsaylor** [comment]
@thomaspaulmann Sure, I like that.

**Comment by thomaspaulmann** [comment]
@Hsaylor I've added a simple implementation on a forked branch. Please have a look on the solution and when you give me a go, I will extend it to the other text document/text methods. After that I will create a PR with all the changes.

Here is a link to the branch: https://github.com/thomaspaulmann/ios-sdk/tree/text-documents

**Comment by thomaspaulmann** [comment]
@Hsaylor Any updates on this? I will extend my example to the whole AlchemyLanguage API and will create a PR. After that we can discuss the solution and fix the details.

**Comment by glennrfisher** [comment]
I really like these changes, @thomaspaulmann. I think they clean up the API and enhance the clarity for our clients.

If you get the chance, we'd love a PR that extends your example. Otherwise, we will probably examine our API and make some of these changes for the v0.5 release in a few weeks.

**Comment by thomaspaulmann** [comment]
Nice to here that you like it @glennrfisher. I will add the changes asap.

**Comment by glennrfisher** [comment]
The AlchemyLanguage service has been deprecated. That portion of the SDK is longer actively maintained, so I'm going to close this issue.
