### ISSUE TITLE
Check error handling for Text to Speech

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#338]
[This question](https://developer.ibm.com/answers/questions/284164/500-forwarding-error-and-inconsistant-error-json-s.html?utm_campaign=answers&utm_medium=email&utm_source=answers-new-question&utm_content=answers-answer-question) on dW Answers suggests that the error response may not always conform to the documentation. Let's check the error response that we would receive and whether it is sufficiently propagated to the user.

(For this particular edge case, it's possible that a decoding error thrown by Freddy that contains the full text of the error message may be sufficient...)

**Comment by mihui** [comment]
Please be noticed that I reopened the [question](https://developer.ibm.com/answers/questions/284164/500-forwarding-error-and-inconsistant-error-json-s/)

**Comment by schen22** [comment]
Thanks @mihui for letting us know! This [PR](https://github.com/watson-developer-cloud/swift-sdk/pull/567) addresses the new changes to error handling in Text to Speech and will be included in the next release of the SDK.

**Comment by mihui** [comment]
Great! @schen22 I updated the [old repository](https://github.com/mihui/speech-ios-sdk) too.
