### ISSUE TITLE
Update type of image parameters

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#353]
This conversation started with @thomaspaulmann in #325. The idea is to improve the API of functions with image parameters by supporting `UIImage` and/or `NSData` parameters instead of `NSURL`.

Here are some points to consider:
- Visual Recognition currently accepts an `NSURL` that can point to either an image file or compressed zip of images. It would probably improve the API if we create separate methods to handle these two cases.
-  These functions can be used to convert a `UIImage` to `NSData`.
  - [`UIImageJPEGRepresentation(_:_)`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/index.html#//apple_ref/c/func/UIImageJPEGRepresentation)
  - [`UIImagePNGRepresentation(_:_)`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/index.html#//apple_ref/c/func/UIImagePNGRepresentation)
- Since the conversion from `UIImage` to `NSData` requires some assumptions (format, compression rate, etc.) it might be useful to expose a function with an `NSData` parameter, too. The `UIImage` function would convert the `UIImage` to `NSData` then call the `NSData` version of the function.
- Since we expect to add support for additional platforms (#129), we want the solution to be simple for both iOS and macOS developers.

**Comment by mkistler** [comment]
This will be fixed in the upcoming major release by accepting all "file"-type parameters as `Data`.
