### ISSUE TITLE
Reorganize project

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#369]
We currently organize the iOS SDK using a single project with a target for each service. As we add support for other platforms (macOS, tvOS, and watchOS), the number of targets will grow from 8 to 64.

We should create a project for each service to help keep the SDK organized. That way, each project has only 4 targets (one for each platform). They can be combined into an Xcode workspace to make development easy and allow us to see all services at once.

**Comment by teddynewell** [comment]
Sounds like this would also speed up the Carthage build times when not all the services are needed.

**Comment by germanattanasio** [comment]
I'm ok as long as the user only need to install one thing

**Comment by glennrfisher** [comment]
I'm going to put this back on the backlog. In hindsight, maybe it's worth the one-time cost of creating all of the targets in the same project (we'd have to create them in each service's project anyway).

More importantly, though, I think this issue deserves to be tackled as part of a larger discussion around continuous integration. With support for iOS, macOS, tvOS, and watchOS, our build time will be 4x as long. That introduces a whole new set of challenges for continuous integration, given that our current build/test runs take about 30 minutes.
