### ISSUE TITLE
Stub tests

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#385]
Stub tests with [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs).

Instead of connecting directly to the service, we can pass through the OHHTTPStubs library. Depending on the state of a flag, we will either (a) connect to the service, save the response to a file, and return the response to the requesting class, or (b) load a saved response from file and return it to the requesting class.

This way, we get the best of both worlds. By programmatically storing responses (and updating them with each release) we can make sure to stay consistent with the services as they change. But with stubbed responses, we can also make our tests run quickly and consistently.

**Comment by glennrfisher** [comment]
When saving the response to a file, we might be able to use reflection to get the name of the current test method. That name will be helpful when reading/writing the stubbed response to a file.

We should also investigate a post-action script for each scheme that copies the files from the simulator to the project directory. See [this page](http://maxao.free.fr/xcode-plugin-interface/build-settings.html#variables) with variables accessible from Xcode.

**Comment by glennrfisher** [comment]
Stephanie made a great [comment](https://github.com/watson-developer-cloud/ios-sdk/issues/407#issuecomment-240831990) in #407 about [Capital One's SWHttpTrafficRecorder](https://github.com/capitalone/SWHttpTrafficRecorder).

**Comment by repjarms** [comment]
Closing as will be addressed in upcoming changes to unit test generation
