### ISSUE TITLE
Programmatically determine downloads directory

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#402]
When testing on a physical device (not the simulator), downloads fail when sent to a "Downloads" directory. We should consider programmatically determining the directory to download to, perhaps using `#if os(...)`. For example, we may want to download to the "Downloads" directory on Mac but "Documents" directory on iOS.

**Comment by glennrfisher** [comment]
I think this would affect Dialog and Retrieve and Rank, but we should find-all in the SDK to look for downloads code.

**Comment by mkistler** [comment]
I think this can be closed. Dialog and Retrieve and Rank have been dropped from the SDK, and only Visual Recognition remains with a method for download, and it does not hard-code the download destination.
