### ISSUE TITLE
Add support for TextToSpeech WebSockets

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#411]
A WebSocket interface was added with the June 23, 2016 update:

> The service now offers a WebSocket interface for synthesizing text to speech. The interface offers the same features as the synthesize method of the HTTP interface. It accepts plain text or text that is marked up with SSML. In addition, it also supports use of the SSML <mark> element to identify the time in the audio at which it finishes synthesizing all text that precedes the mark. For more information, see Using the WebSocket interface.

See [Using the WebSocket Interface](https://www.ibm.com/watson/developercloud/doc/text-to-speech/websockets.shtml).

**Comment by repjarms** [comment]
This will be included in an upcoming major release (targeting October 2019)

**Comment by germanattanasio** [comment]
Where are we with this @repjarms ?
