### ISSUE TITLE
Add Opus decoding

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#520]
Opus can significantly reduce the file size and save the bandwidth required to download audio. It would be helpful to add support for _decoding_ Opus audio files to help users save space and bandwidth.

**Comment by schen22** [comment]
For reference: 
[Opus Decode Docs](https://www.opus-codec.org/docs/html_api-1.1.0/group__opus__decoder.html#details)
[Sample Opus Decode iOS implementaton](https://github.com/watson-developer-cloud/speech-ios-sdk/blob/master/watsonsdk/opus/OpusHelper.m#L159)
[Speech To Text Encoder](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Source/SpeechToTextV1/SpeechToTextEncoder.swift)

Currently the `synthesize` function returns `.wav` formats [seen here](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Source/TextToSpeechV1/TextToSpeech.swift#L215). We can either directly return the `.opus` files to the user and have users provide a way to directly playback the opus file, or decode the opus file to `.wav` for our users.

**Comment by schen22** [comment]
Other helpful tools:
https://tools.ietf.org/html/rfc7845

**Comment by schen22** [comment]
Progress Update: Conversion of [Objective-C Implementation](https://github.com/watson-developer-cloud/speech-ios-sdk/blob/master/watsonsdk/opus/OpusHelper.m#L159) to Swift implementation is complete. 

@sccheng and I have added Opus decoding and have constructed a framework to return a decoded Opus audio file; however testing and continued debugging is needed. Feel free to check out the [opus-tts] (https://github.com/watson-developer-cloud/swift-sdk/tree/opus-tts) branch to see progress.

**Comment by sccheng** [comment]
@schen22 and I have had a productive week! Bug fixes are done - Opus decoding works properly :) We tested importing the PCM data to Audacity and confirmed that it plays back as expected. I've opened a new issue #583 to add WAV headers to the PCM data, so we should be able to close this issue now.

**Comment by schen22** [comment]
Sounds great to me. Thanks for all the hard work you put into debugging the Opus decoding issue! Really awesome work.

**Comment by BilalMaarbani** [comment]
hello, can anyone help me to build a small application on swift that read mp3 then convert it to opus codec ? please I need help
