### ISSUE TITLE
Revise Objective-C tutorial

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#521]
Since we've removed the Alamofire and Freddy dependencies, we should update the Objective-C tutorial to be consistent with the latest version of the SDK.

It would be great if we could make the Objective-C tutorial as similar as possible to the quick start guide. Then instead of referring to it as the Objective-C tutorial, we can just call it "Quick Start Guide (Objective-C)".

**Comment by EricMentele** [comment]
This was killing me! So glad I found this.
