### ISSUE TITLE
Compress HTTP traffic

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#539]
Consider compressing requests with gzip to save network bandwidth. It's possible that `NSURLSession` does this automatically, but I doubt it.

(This [article](https://clintmartin.net/2016/03/15/gzipping-ios-apps.html) seems to suggest that `NSURLSession` will automatically _decompress_ a gzip response, but it's unclear whether the _request_ is compressed.)

**Comment by germanattanasio** [comment]
We need to check if compression is enabled in the platform(DataPower). 
Last time I checked it wasn't enabled but I will let you know

**Comment by germanattanasio** [comment]
DataPower supports compression so you can enable it on the sdk. I bet it's probably a small change in the HTTP layer.
