### ISSUE TITLE
Update libogg and libopus build scripts

### ISSUE THREAD

**Issue by schen22** [watson-developer-cloud/swift-sdk#548]
For reference:
- [Opus-iOS Repository](https://github.com/chrisballinger/Opus-iOS)
- [Related Issue](https://github.com/chrisballinger/Opus-iOS/issues/3)
- [Related Issue](https://github.com/chrisballinger/Opus-iOS/issues/1)

Note issue #540

**Comment by glennrfisher** [comment]
Complete with #675.
