### ISSUE TITLE
Getting no data from STT after switching to 0.11.0

### ISSUE THREAD

**Issue by troyibm** [watson-developer-cloud/swift-sdk#552]
You'll hate this issue, but I need to track this somewhere.

I had been using 0.9.1 release with new app we are building.  Was getting the "stream must be 100 bytes" problem intermittently, but looks like that was fixed so decided to build with 0.11.0.  Updated Cartfile.resolved and pulled down the binary but wouldn't work with Swift 3.0.1 (understandable) so used --no-use-binaries command and built the frameworks instead.

Tested with simulator and all worked great so distributed build to others via hockeyapp and then they reported that STT wasn't working at all.  No text would appear when talking as it was doing before.  So, I installed on my device and got same problem.  Check microphone permission setting and it was enabled.  Deleted and installed and still same problem.  I did finally see some text, but it was like 1 in 10 tries.  Even the TTS wasn't working reliably. I went back to running on simulator and it worked fine.  Weird.

So, right now, I'm downgrading to 0.10.0 to see if that does better.  I'll update the issue once build and test was done.

**Comment by troyibm** [comment]
Dropped back to using 0.10.0 and STT worked on device without a hitch.

**Comment by sccheng** [comment]
Hi @troyibm,

I've been doing some testing today - I made a new app that creates an instance of SpeechToText using version 0.11.0 of the SDK. The app just has a button which, when pressed, calls `speechToText.recognizeMicrophone()` and prints out the response.

I've been testing on a physical iPhone 6s, and it's been very consistent with giving me back a response.

Would you be able to give me some more information on your error? Do you still see it now when using version 0.11.0?

**Comment by troyibm** [comment]
@sccheng I can provide more info next week.  I'm at CES this week.

**Comment by troyibm** [comment]
@sccheng 
This might be something I'm doing in my code, but there is definitely a difference in how my app plays text and gets data from the microphone between 0.10.0 and 0.11.0.  When I build with 0.11.0, after launching the app, I get nothing back from the microphone and the playing of speech is loud.  If I restart the dialog from within the app (via Back button on navigation bar), the speech is low but I get data back from microphone and app works correctly.  

I don't get any of this weirdness when building with 0.10.0.  On first launch of the app, the speech is loud and data received from the microphone.  Restarting the dialog via the Back button performs the same way (speech is loud and microphone works).


I'll look into this more after lunch.

**Comment by sccheng** [comment]
Hmmm... interesting. Are you modifying the shared AVAudioSession, by any chance? We did change some things around how we were setting the shared AVAudioSession in 0.11.0, perhaps that's what's causing the issue.

**Comment by troyibm** [comment]
There are no calls directly to AVAudioSession in my code.  I do use AVAudioPlayer though.

**Comment by sccheng** [comment]
Do you use `SpeechToText.recognizeMicrophone` or `SpeechToTextSession.startMicrophone`?

**Comment by troyibm** [comment]
SpeechToTextSession.startMicrophone

**Comment by sccheng** [comment]
Ahh, so it seems like that could be the issue.

Starting with version 0.11.0, we updated `SpeechToTextSession.startMicrophone` so that it's more customizable. This also means that we do less of the setup, to allow users to have more control over their shared instance of AVAudioSession.

Long story short, for `SpeechToTextSession.startMicrophone`, we've removed the lines where we were setting up AVAudioSession for the user.

If you'd like to continue using the SDK as you were previously, you can try using `SpeechToText.recognizeMicrophone`, which *does* do the setup for AVAudioSession for you, but may give you less control over AVAudioSession.

Otherwise, I'd suggest you add these lines to a setup function somewhere: 
```
try! AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, 
               with: [.mixWithOthers, .defaultToSpeaker])
try! AVAudioSession.sharedInstance().setActive(true)
```

Let me know if this works, or if you still experience any issues!

**Comment by sccheng** [comment]
Hey @troyibm, are you still seeing problems with SpeechToText? If not, I'll go ahead and close out this issue.

**Comment by troyibm** [comment]
Sorry @sccheng.  I wasn't able to try this to see if that was the problem.  But I trust you and fine with you closing this issue.  Thanks.

**Comment by sccheng** [comment]
Ahh, no worries! I'll go ahead and close the issue for now, but feel free to reopen it or create another if you notice you're still experiencing any problems.
