### ISSUE TITLE
[speech-to-text] Investigate range exceeding data length crash, PR #554

### ISSUE THREAD

**Issue by schen22** [watson-developer-cloud/swift-sdk#556]
Investigate if #554 really fixes issue when no data is attached to the payload. 

- [ ] Test SDK when no data is returned.
- [ ] Test with file that has only 12 byte WAV header
- [ ] Test with file that has 12 byte WAV header, and only 1 byte of information after. 
- [ ] Recreate error referenced in the PR. 

Most likely will need to update `dataToUTF8String` and `isWavFile` functions.

**Comment by schen22** [comment]
@tigersoft - could you give us more information on creating the error you had received, and test out the changes I made on the branch `data-length-crash-TTS`? 

Thanks in advance!

**Comment by tigersoft** [comment]
> could you give us more information on creating the error you had received

Given that the nature of the problem probably has to do with network communications, I am sorry but I do not have a specific reproducible scenario to cause the issue. To test out my fix, I introduced some temporary testing code inline that would explicitly cause the problem.
