### ISSUE TITLE
how to specify number of rows to retrurn for retrieveAndRank.searchAndRank

### ISSUE THREAD

**Issue by BrianJZhang2** [watson-developer-cloud/swift-sdk#559]
Using RetrieveAndRankV1 for our iOS app, is there an API that we can use to specify the rows to return?

**Comment by sccheng** [comment]
Hey @BrianJZhang2, we've now added parameters for the `search`, `searchAndRank`, and `rankResults` calls where you can pass a number to specify the number of answers/documents you want returned. You can look at PR #563 for more details.

Thanks for bringing this to our attention!
