### ISSUE TITLE
carthage update never completes

### ISSUE THREAD

**Issue by bjulbricht** [watson-developer-cloud/swift-sdk#564]
We are having trouble using carthage update with a Cartfile that contains the following:

github "watson-developer-cloud/ios-sdk"

On the terminal window, the following messages display but the update never completes.

*** Fetching ios-sdk
*** Fetching swift-sdk

I noticed that a Cartfile was added to in commit https://github.com/watson-developer-cloud/swift-sdk/commit/a8b1a763452f137006cdc72bc2d00c7a70f4496c#diff-60bb710c5144ead8f8cb73a22de579ab yesterday. That is when we started seeing problems with our Starter doing the carthage update.

**Comment by stupergenius** [comment]
Yes! We're also seeing this. Sometimes I get something like:

```shell
*** Fetching swift-sdk
[1]    45331 illegal hardware instruction  carthage bootstrap --verbose --platform iOS
```

Other times it just hangs.

Pertinent versions:

```bash
$ git --version
git version 2.10.1 (Apple Git-78)
$ carthage version
0.18
$ swift --version
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

**Comment by schen22** [comment]
I'm looking into why Carthage is hanging now. I tested `carthage update` before publishing the release yesterday and Carthage had completed building dependencies successfully. I'll post updates accordingly.

**Comment by schen22** [comment]
@stupergenius, @bjulbricht: As a quick fix to allow you to build the sdk dependencies, please specify version 12 of the app within your Cartfile:

`github "watson-developer-cloud/ios-sdk" ~> 0.12.0`

The renaming must have affected Carthage somehow. Rebuilding the binaries now to see if that'll change anything.

**Comment by schen22** [comment]
Ah - whoops. Good point about the new Cartfile that was added. That seemed to have created a loop while executing `carthage update`. I'm regenerating the binaries one last time now so the Cartfile will be removed when grabbing the repo, but if you specify the latest commit in your Cartfile, you should be able to grab v13:

`github "watson-developer-cloud/ios-sdk" "35aa20bcb8d8e733a8743449309db42de356655f"`

**Comment by schen22** [comment]
A Cartfile with the following: 

```
github "watson-developer-cloud/swift-sdk"
``` 
works when I run `carthage update --platform iOS` and `carthage update` in a sample project I've made.

**Comment by vherrin** [comment]
Thanks Sarah for the quick turnaround!
