### ISSUE TITLE
Update Readme to explain creating a Cartfile

### ISSUE THREAD

**Issue by ereneld** [watson-developer-cloud/swift-sdk#580]
I didn't use any cartfile before and the Cartfile creating step is missing on Readme or the default Cartfile should come with project as well. 

you may add Cartfile creating to Readme something like: 

From the command line, navigate to your project directory.
`touch Cartfile`
Now the Cartfile is created, make it executable with:
`chmod +x [YourDirectory/Cartfile]`

**Comment by schen22** [comment]
That's a good point, I'll open an issue to update the README to make creating a Cartfile clearer.

Another good tool is to run the following command:

`swift package init --type executable` in the directory your project is living. This command essentially creates the Cartfile as an executable.

Then to download the dependencies specified in the Cartfile (if any), run `swift package fetch`.

**Comment by sccheng** [comment]
I've gone ahead and opened a master issue to track all the things we are missing in our README, so I'll go ahead and close this issue for now.
