### ISSUE TITLE
Consider an abstraction for synthesized audio

### ISSUE THREAD

**Issue by sccheng** [watson-developer-cloud/swift-sdk#587]
Currently, in the `synthesize` method of TextToSpeech, we return a generic Data object to the user. We are also using an if/else statement to determine how to handle different audio types. Specifically, if the requested audio type is WAV, we'll repair the wav headers if needed and return the Data to the user. If the requested type is Opus, we'll decode the Opus data to PCM and add WAV headers, then return this to the user.

Let's see if a TextToSpeechAudio class/struct, or something similar, could be useful in place of the generic Data return type. We can pass the data received from the TTS service and handle it within TextToSpeechAudio.

Here's an example of what we could do, based on a brainstorming session with Glenn and Sarah a few weeks ago: [TextToSpeechAudio.txt](https://github.com/watson-developer-cloud/swift-sdk/files/807439/TextToSpeechAudio.txt)

**Comment by glennrfisher** [comment]
Reviewing the notes, I think this is an interesting idea. Some thoughts:

- This abstraction allows users to access the opus data directly. As it stands, the SDK automatically converts opus to wav, and returns the wav data to the user. Other formats, however, are returned as raw data (e.g. FLAC). Seems like an inconsistency in the SDK.
- It's nice to have a `play` function, immediately available on the return type.
- It's nice to carry-around the format of the data, although I think developers can do that themselves, so it's not a strong motivation for creating the abstraction.
- I worry about the `convertToWav` function for two reasons, (1) it's an extra step for developers, who might now be expecting a wav function, and (2) it's awkward for wav files and unsupported formats. That function might have to `throw` an error for formats like FLAC that are unsupported.
