### ISSUE TITLE
Cross check NLU features are updated with API Reference rather than with API explorer

### ISSUE THREAD

**Issue by schen22** [watson-developer-cloud/swift-sdk#592]
[API Reference](https://www.ibm.com/watson/developercloud/natural-language-understanding/api/v1/)

There are a few mismatches between the two docs unfortunately, but we should make sure to support all the features. Already mentioned to NLU team and they say to use the API Reference for now as they update the API explorer.

**Comment by glennrfisher** [comment]
Just a note that the Swagger specification for Natural Language Understanding has been considerably updated. There may still be missing features in the Swift SDK (see #600), but we should be able to rely on the Swagger specification / API Explorer now.
