### ISSUE TITLE
Speech To Text iOS 10 bug

### ISSUE THREAD

**Issue by triceam** [watson-developer-cloud/swift-sdk#595]
1. I recently noticed while building a new app on iOS 10 that uses text to speech that you now have to specifically request permission with a description in Info.plist (`NSMicrophoneUsageDescription`) in order for this to work.  This should be documented.

2. After granting permission, the audio source switches, and I could only get it to work if I plugged in ear buds.  It seems like the default speakerphone setting wasn't accepted or was changed.

**Comment by triceam** [comment]
also, looks like stt fails if you go into the background and back into the foreground again.  you can re-initialized it to get things working again, but without doing so, then everything *appears* to work (no errors), but no mic data is ever received.

**Comment by sccheng** [comment]
Hi @triceam,

Thanks for pointing out the microphone permissions that need to be included in the Info.plist. You're right, we need to update our README to include this information! I'll go ahead and open a new issue in a bit to document that that needs to be done.

In terms of your issues with the audio source, are you using the `recognizeMicrophone` method in `SpeechToText` or the `startMicrophone` method in `SpeechToTextSession`? With the `SpeechToText` method, you shouldn't need to modify the AVAudioSession. However, with the `SpeechToTextSession` method, you'll need to manage the AVAudioSession yourself, like so:
```
try audioSession.setCategory(AVAudioSessionCategoryPlayAndRecord, with: [.defaultToSpeaker, .mixWithOthers])
try audioSession.setActive(true)
```
This is something that I know is currently missing from our README, so I'll go ahead and add it to the new issue as well.

Let me know if that fixes your issues. If not, we can look into it a bit more.

**Comment by triceam** [comment]
Using sessions.  I actually have that already:

```

        do {
            try session.setActive(false)
            try session.setCategory(AVAudioSessionCategoryPlayAndRecord, with: [.mixWithOthers, .allowBluetooth, .defaultToSpeaker])
            try session.overrideOutputAudioPort(.speaker)
            try session.setActive(false)
            
            session.requestRecordPermission { (granted) in
                if(granted) {
                    print("microphone permission granted")
                }
                else {
                    print("microphone permission denied")
                }
            }
        }
        catch {
            print("Error setting up audio preferences")
        }
```

What I'm seeing is that if the app goes into the background, then back into the foreground, STT fails on the first attempt.  After the first attempt times out, it starts working again.

**Comment by triceam** [comment]
OK, got it working.  Just realized that after changing settings, I was setting active to false, not true.   Even so, this was through a lot of trial and error.  Would be great to add this to docs.

**Comment by sccheng** [comment]
Ahh, good to hear that you were able to get it working!! Thanks again for pointing out things that are missing in our README, I opened up another issue to track things missing in our README, and have added the things you've found to that list as well. I'll go ahead and close this issue now.
