### ISSUE TITLE
Add support for workspaces and endpoints within Conversation API

### ISSUE THREAD

**Issue by schen22** [watson-developer-cloud/swift-sdk#601]
- [ ] support endpoints listed in the Conversation [API explorer](https://watson-api-explorer.mybluemix.net/apis/conversation-v1).
- [ ] Use Swagger generator to generate the endpoints and see the differences.
- [ ] Provide feedback document for any potential differences between expected output and generated output.
- [ ] Must create and pass tests per endpoint and/or model created.

**Comment by sccheng** [comment]
Support for workspaces, intents, examples, and counterexamples were added in #619
