### ISSUE TITLE
Swift 3.1 compatibility

### ISSUE THREAD

**Issue by no404here** [watson-developer-cloud/swift-sdk#605]
I was using the Visual Recognition V3 framework, but since Apple updated the swift version to 3.1, I cannot compile my application anymore, we need to re-compile the frameworks

**Comment by sccheng** [comment]
Hi @no404here,

Thanks for opening this issue. We'll try to publish a release in the next few days! 

In the meantime, you can try re-installing the SDK dependencies with `carthage update --no-use-binaries` and see if that fixes your problems!

**Comment by tylermilner** [comment]
@sccheng The `carthage update --no-use-binaries` did not work for me. It fails when compiling the "SpeechToTextV1" just like the `carthage update` command.

![image](https://cloud.githubusercontent.com/assets/1720304/24466567/f154ab40-1476-11e7-98ac-7859fe1764c7.png)

**Comment by sccheng** [comment]
Hi @tylermilner,

Yup, you're totally right. I became aware of it yesterday when trying to create a release. I'm working to fix some bugs, and so far, it looks promising! I hope to publish a release this afternoon to fix all of this.

**Comment by sccheng** [comment]
Hi all, as of the release last week (v0.14.3), the SDK now supports Xcode 8.3/Swift 3.1. I'll go ahead and close this issue now.

**Comment by MatthewWaller** [comment]
Hello. I'm still getting issues when trying to do a Carthage update. Same error screenshot above. Is it working for you? Thanks!

**Comment by sccheng** [comment]
Hi @MatthewWaller, that's odd...Hmm. Does it say it's pulling down v0.14.2 or v0.14.3? If you grab v0.14.3, things should work properly.

**Comment by MatthewWaller** [comment]
Yes, I get: "Task failed with exit code 65: ... Release -derivedDataPath /Users/matthewwaller/Library/Caches/org.carthage.CarthageKit/DerivedData/ios-sdk/v0.14.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build."
I tried clearing the cache for CarthageKit and rebuilding, but I got the same response. Is there something else I need to do?

**Comment by MatthewWaller** [comment]
If I build the framework from the cloned Watson SDK repository, it builds fine. It's just the Carthage update I'm having trouble with.

**Comment by sccheng** [comment]
Hmm, @MatthewWaller, I'll take a look. Are you just doing a `carthage update`? And in your Cartfile, you have `github "watson-developer-cloud/ios-sdk"`?

**Comment by MatthewWaller** [comment]
yep. Just a carthage update, and the Cartfile matches github "watson-developer-cloud/ios-sdk"

**Comment by MatthewWaller** [comment]
Well, if it's just me, I'll keep working at it and try to clear caches somewhere else. Not sure how to get it going. Thanks, nonetheless.

**Comment by sccheng** [comment]
Thanks for your comments, @no404here!

@MatthewWaller, I've tried doing the carthage update, but I can't seem to reproduce your error. If you have any additional steps, or see any specific way to recreate your errors, feel free to open up a new issue and we can take another look!
