### ISSUE TITLE
Consider adding a `Watson` prefix to all module names

### ISSUE THREAD

**Issue by gmosx** [watson-developer-cloud/swift-sdk#611]
e.g. instead of:

```
import ConversationV1
```

have:

```
import WatsonConversationV1
```

In this example Conversation is a common word that may be already used in client applications.

**Comment by sccheng** [comment]
Hi @gmosx,

Changing our module name would require all other users of the SDK to update their import statements. Additionally, I believe that appending the version numbers the service name (`ConversationV1`, `PersonalityInsightsV3`, etc) should be unique enough.

Would you be able to provide an example where you are experiencing this conflict? Any extra information you have would be appreciated!

**Comment by gmosx** [comment]
At least you could use the `Watson` prefix in future APIs.

The `Vx` postfix is not good enough. For example I already have my own Conversation module (that does something different) and having Conversation, ConversationV1 at the same time is not nice.

**Comment by germanattanasio** [comment]
Thanks for the suggestion @gmosx but after some discussions with the team we would prefer to keep the names as they are.
