### ISSUE TITLE
[NLU] Getting nil value for sentiment score

### ISSUE THREAD

**Issue by Ashxvi** [watson-developer-cloud/swift-sdk#612]
Hi there,

I'm trying to get the sentiment score with the following code : 

```
        let concepts = ConceptsOptions(limit: 5)
        let features = Features(concepts: concepts)
        let parameters = Parameters(features: features, url: url)
        let naturalLanguageUnderstanding = NaturalLanguageUnderstanding(username: username, password: password, version: version)
        let failure = { (error: Error) in print(error) }
        
        naturalLanguageUnderstanding.analyzeContent(withParameters: parameters, failure: failure) {
            results in
            print (String(describing: results.sentiment?.document?.label!))
        }
```
I'm always getting nil value, but when I've tried the following cURL command It works fine : 

`curl -u "username":"password" "https://gateway.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2017-02-27&url=https://www.moroccoworldnews.com/2017/03/212639/bmce-bank-africa-records-historic-net-income/&features=sentiment,keywords"`

Thanks in advance,

**Comment by sccheng** [comment]
Hi @Ashxvi,

I think your problem might be the line where you create the `features` variable. Currently, you're doing this:
```
let features = Features(concepts: concepts)
```

To make sure that you're including sentiment as a parameter, make sure that you actually create the `features` variable like so:
```
let features = Features(sentiment: SentimentOptions(document: true))
```

You can refer to our [tests](https://github.com/watson-developer-cloud/swift-sdk/blob/master/Tests/NaturalLanguageUnderstandingV1Tests/NaturalLanguageUnderstandingV1Tests.swift#L417) for more examples! We have 2 tests currently, where we're requesting the Sentiment feature with and without targets.

Let me know if this fixes your problem, or if the sentiment values still show up as nil.

**Comment by Ashxvi** [comment]
Thank you @sccheng . It works fine now!
