### ISSUE TITLE
Fix warnings resulting from the update to Xcode 8.3/Swift 3.1

### ISSUE THREAD

**Issue by sccheng** [watson-developer-cloud/swift-sdk#614]
A few warnings have shown up since we updated to Xcode 8.3/Swift 3.1.

Some of these warnings  show up in Xcode:
![image](https://cloud.githubusercontent.com/assets/5377024/24629142/a175b30c-187d-11e7-841e-43a05193e195.png)

We're also getting some warnings from the `carthage update` command and the `carthage build --no-skip-current` commands. There are a lot of the same warnings:
```
<unknown>:0: warning: argument unused during compilation: '-iapinotes-modules /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/arm64'
<unknown>:0: warning: argument unused during compilation: '-iapinotes-modules /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/armv7'
```

**Comment by sccheng** [comment]
We were able to remove the SpeechToText warnings by removing the modulemaps in our project!

The warnings about `iapinotes-modules` could be related to [this issue](https://github.com/Carthage/Carthage/issues/1877), and might be a bug in Xcode itself. More research needed.

**Comment by glennrfisher** [comment]
I can't speak to Xcode 8.3 and Swift 3.1, but I made changes to avoid all warnings when building with Xcode 9 and Swift 4. The only remaining warnings come from the Starscream dependency, which will be updated with #667.
