### ISSUE TITLE
[speech-to-text] SpeechToTextSession not working on devices

### ISSUE THREAD

**Issue by gikokopev** [watson-developer-cloud/swift-sdk#615]
The SpeechToTextSession when used on device isn't receiving any transcription results from service, when deployed on device.
The exactly the same issue exist in the demo app also, so reproduction is explained for it instead. It looks like the device isn't streaming any data at all.

Note: The issue doesn't exist on simulators only devices!
- Setup the example application from https://github.com/watson-developer-cloud/speech-to-text-swift, following the instructions. 
  Before build & run replace in MicrophoneViewController.swift the lines

```
@IBAction func didPressMicrophoneButton(_ sender: UIButton) {
        streamMicrophoneBasic()
    }
```

```
@IBAction func didPressMicrophoneButton(_ sender: UIButton) {
        streamMicrophoneAdvanced()
    }
```

- Build for device and run on it. Press tab "Microphone" select "Start Microphone"
- Expecting to get onResults, onMicrophoneData, onPowerData (different than -120)
- Actual behaviour 
      NO onResult, onMicrophoneData, only some default onPowerData,
      woking callbacks onConnect, onDisconect
      when SpeechToTextSession stopMicrophone and stopRequest an onError is receiving this message: "Stream was 0 bytes but needs to be at least 100 bytes."
- Xcode version 8.2.1 
- ios-sdk version 10 & 9 were tested. Both not working.
- ios version targeting - 9
- microphone has permissions for this app

**Comment by gikokopev** [comment]
**Resolved**

Unlike SpeechToText, SpeechToTextSession doesn't set any audio category by default. This fixes the issue

```
do {
            try AVAudioSession.sharedInstance().setActive(false)
            try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with: [.mixWithOthers,  .defaultToSpeaker])
            try AVAudioSession.sharedInstance().setActive(true)
       }
       catch{
         print("Error setting up AVAudioSession category")
       }
```

**Comment by GaneshManickam** [comment]
Hi @gikokopev where to add the code mentioned above. I am also facing the same issue.
