### ISSUE TITLE
Resolve VisualRecognition `keyNotFound` error

### ISSUE THREAD

**Issue by schen22** [watson-developer-cloud/swift-sdk#621]
Customer receives error `keyNotFound("images")` when running externally on phone; however it works fine when using simulator.

**Comment by vherrin** [comment]
This is working correctly on my iPhone so any further details related to this issue?

**Comment by tarszewski** [comment]
I have the same error keyNotFound("images"). Xcode Version 8.3.2 and iPhone 5s iOS 10.3.1. Error is in method visualRecognition.classify(image: url, failure: failure) in failure closers.

**Comment by vherrin** [comment]
From Jeff Laurenza - Here are the versions the customer is using: Xcode Version 8.2.1 and Version 0.15.0 of the SDK

**Comment by sccheng** [comment]
I've been doing some testing, and so far, I'm unable to reproduce this issue. 

@tarszewski, could you give me more details? For example, could you let me know what image you're trying to classify?

**Comment by tarszewski** [comment]
For many different photos from different urls is the same error:

For examples:

```
let url = "https://images-na.ssl-images-amazon.com/images/G/01/img15/pet-products/small-tiles/23695_pets_vertical_store_dogs_small_tile_8._CB312176604_.jpg"
        let failure = { (error: Error) in print(error) }
        visualRecognition.classify(image: url, failure: failure) { classifiedImages in
            if let classifiedImage = classifiedImages.images.first { print(classifiedImage) }
```

On simulator everything works good.

**Comment by schen22** [comment]
@tarszewski - I'm currently testing on Xcode 8.3.2 and an iPhone 5s iOS 10.3.1 and I wasn't able to reproduce the error you're seeing. Here's the sample project we created using to test the image you mentioned. 
[test-vr.zip](https://github.com/watson-developer-cloud/swift-sdk/files/959131/test-vr.zip)

**Comment by tarszewski** [comment]
In your sample project a have the same error. I don't know what else I could do.

**Comment by schen22** [comment]
It's hard to tell what's going on, especially when I can't reproduce the error. My guess is that it has something to do with the symlink between your Xcode version and device. I would probably try rebooting Xcode, disconnecting your phone, rebooting your phone again. Otherwise if that still doesn't work your issue seems somewhat related to what's being discussed [here]( https://gist.github.com/steipete/d9b44d8e9f341e81414e86d7ff8fb62d). 

Because this issue doesn't seem related to the SDK itself, I'm going to go ahead and close this issue. Feel free to add more details and comments if you think otherwise.

**Comment by tarszewski** [comment]
hmm. I restored my iPhone to factory settings and it worked fine but after 2 days i have the same error. I installed only few app.

**Comment by allforcode** [comment]
It seems If the language running on the device is not supported by VisualRecognitionV3, it would have this problem.

So, it should work if you could add a parameter ```language: "en"```  to ```classify``` function.
```
visualRecognition.classify(imageFile: fileURL, language: "en", failure: whenFailure, success: {
                (classifiedImages ) in
...
})
```
