### ISSUE TITLE
Not able to find whether user speaking or not while recording time using this watson api for iOS Objective-C

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [watson-developer-cloud/swift-sdk#626]
I am working an app in iOS, its like speech to text. In that, we using Watson Framework in Objective-C, its working fine, but, if I initiated speak button, it will stream for 20 to 30 seconds, and its not recognising whether user speaking or not. I trying to check after initiated speaker button, its should have to check whether user speaking or not, if not need to show some popup.

How to do this, Can anyone help me.

Thanks

**Comment by sccheng** [comment]
Hi @AnilkumarRabhasa,

Thanks for opening this issue! Which methods are you using to communicate with the Speech to Text service? Could you add a code snippet here and/or give me more information about your setup? Also, please let me know which version of the SDK you are using. This way, I can try to reproduce your issue on my end!

At first glance, however, your error (not recognizing when users are speaking) reminds me of [this](https://github.com/watson-developer-cloud/swift-sdk#important-notes). If you are using `SpeechToTextSession`, you need to remember to manage your `AVAudioSession` shared instance properly.

**Comment by glennrfisher** [comment]
Hi @AnilkumarRabhasa. Unfortunately, we no longer support or update the Objective-C SDK for Speech to Text. Have you tried using the Swift SDK?

**Comment by AnilkumarRabhasa** [comment]
Oh, its really shocked @glennrfisher , We are at final step to submit the app to appstore. But, suddenly you telling like this no longer supporting Objective-C. Can you provide the steps to how can I replace the SDK to existing Objective-C code, it would be helpful to us.

**Comment by glennrfisher** [comment]
Just to clarify, @AnilkumarRabhasa, the Objective-C based "Watson Speech iOS SDK" was [deprecated][1] in December of 2015 and replaced with this repository, the "Watson Swift SDK".

The readme links to [this tutorial][2] with a step-by-step guide for using the Swift SDK in an Objective-C application. Hope that helps!

[1]: https://github.com/germanattanasio/speech-ios-sdk/commit/02a89d0597aa223a03470be2e59875885f725348#diff-04c6e90faac2675aa89e2176d2eec7d8
[2]: https://github.com/watson-developer-cloud/swift-sdk/blob/master/docs/objective-c.md

**Comment by AnilkumarRabhasa** [comment]
Its showing Carthage, is there any option for CoCoa Pods to install this framework?

**Comment by glennrfisher** [comment]
Unfortunately, the Watson Swift SDK does not support Cocoapods at the moment. We may add support for Cocoapods in the future, but don't know when that would happen.

**Comment by AnilkumarRabhasa** [comment]
Can you please provide any link/example for replace with existing objective C Watson SDK with new Swift SDK and how to add them to my existing Objective C project step by step, it will be helpful me.

**Comment by glennrfisher** [comment]
The readme links to [this tutorial][2] with a step-by-step guide for using the Swift SDK in an Objective-C application. Hope that helps!

[2]: https://github.com/watson-developer-cloud/swift-sdk/blob/master/docs/objective-c.md

**Comment by AnilkumarRabhasa** [comment]
Its showing only Tex to Speech, We need Speech to Text also

**Comment by AnilkumarRabhasa** [comment]
@glennrfisher really thanks so much for your quick response, here I got strucked, in Speech to text objective-c version we have following method

            [stt recognize:^(NSDictionary* res, NSError* err){
But, in Swift version where can I get, Can you please provide for Speech to Text Bridging with Objective-C like you provide link for Text To Speech following

https://github.com/watson-developer-cloud/swift-sdk/blob/master/docs/objective-c.md

**Comment by AnilkumarRabhasa** [comment]
@sccheng @glennrfisher @jthomas @tmarkiewicz @bfaist I am waiting for your valuable answer for above issue, it will resolve my issue for objective-C project.

**Comment by glennrfisher** [comment]
@AnilkumarRabhasa Please refer to the [Speech to Text section](https://github.com/watson-developer-cloud/swift-sdk#speech-to-text) of the readme for specific code examples.

**Comment by tmarkiewicz** [comment]
@AnilkumarRabhasa This question is more appropriate for StackOverflow or dwAnswers. Please post your question there with the appropriate tags. Typically the issues on a Github repo pertain to bugs/problems with the code itself as opposed to questions on how to use or implement it.

**Comment by AnilkumarRabhasa** [comment]
@glennrfisher I tried few methods, but as per you provided readme Text to Text Objective-C bridging with swift is very clear, like that I am looking forward and I got strucked with Speech to Text bridging for voice recognition, if error comes, or success request, like this way to show in UI.

@tmarkiewicz I already raised ticket in Stackvoerflow, but no one has answered so far, because this bridging has no one has awareness on Watson SDK, please check following.

https://stackoverflow.com/questions/45814906/watson-swift-sdk-for-objective-c-bridging-for-speech-to-text

**Comment by AnilkumarRabhasa** [comment]
@sccheng @glennrfisher @jthomas @tmarkiewicz @bfaist I am waiting for your valuable answer for above issue, it will resolve my issue for objective-C project.

**Comment by bfaist** [comment]
I followed the [Objective-C tutorial](https://github.com/watson-developer-cloud/swift-sdk/blob/master/docs/objective-c.md) and it works.  So you will be writing a wrapper API for the Swift SpeechToText code and then reference this in the Obj-C code.

**Comment by AnilkumarRabhasa** [comment]
@bfaist I followed that code for Text to Speech, its working fine, I am expecting Speech to Text code the way you provided Text to Speech for bridging.

**Comment by AnilkumarRabhasa** [comment]
@bfaist I am waiting for your valuable suggestions for Speech to Text speech integration for bridging to Objective-C project. Can you please do reply?

**Comment by bfaist** [comment]
Does this example help?  [https://github.com/bfaist/WatsonSpeechToTextObjC](https://github.com/bfaist/WatsonSpeechToTextObjC)
