### ISSUE TITLE
WebSocket closed with reason[1000]: Manually terminating socket connection

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [watson-developer-cloud/swift-sdk#628]
I have integrated to my iOS app. Its working fine, but some times while converting speech to text, its showing following error.

WebSocket closed with reason[1000]: Manually terminating socket connection

Please help me how to fix this.

**Comment by sccheng** [comment]
Hi @AnilkumarRabhasa,

Hmm...I'm sorry you're running into this problem! Could you give me more information on when you see this error? What is currently happening in your app when this occurs? Which methods in the SDK are you using, and what version of the SDK is this?

I'd appreciate if you can include some sample code so that I can try to reproduce this issue on my end. Thank you!!

**Comment by AnilkumarRabhasa** [comment]
I am using Objective-C version, can you pls help me in that issue, its getting huge effect on my app.

**Comment by AnilkumarRabhasa** [comment]
I think its same like this https://github.com/germanattanasio/speech-ios-sdk, same version sdk.

**Comment by glennrfisher** [comment]
Hi @AnilkumarRabhasa. This is normal behavior for the underlying WebSocket that is used to stream data to/from the Speech to Text service.

A WebSocket status code of 1000 is a `CLOSE_NORMAL` event. The [Mozilla Developer Network][1] describes it as: "Normal closure; the connection successfully completed whatever purpose for which it was created." In other words, you would expect to receive a 1000 status code when the socket is closed without an error.

The socket may be closed by either the client or the server. In the case of Speech to Text, your app might close the socket after sending an audio file, or the server might close the socket after a timeout (30 seconds of non-speech audio, by default).

Please note that we no longer support or update the Objective-C SDK for Speech to Text. We suggest you try the Swift SDK.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent
