### ISSUE TITLE
Speech to Text    Error

### ISSUE THREAD

**Issue by Buliceli** [watson-developer-cloud/swift-sdk#637]
Speech to Text: Error Domain=com.ibm.watson.developer-cloud.SpeechToTextV1 Code=0 "Session timed out." UserInfo={NSLocalizedFailureReason=Session timed out.}

Speech to Text: Error Domain=WebSocket Code=1011 "see the previous message for the error details." UserInfo={NSLocalizedDescription=see the previous message for the error details.}

Speech to Text: Disconnected

**Comment by glennrfisher** [comment]
Hi @Buliceli. Is there any more information you could provide?

This is probably a [timeout][1] from the Speech to Text service:

> To preserve resources when you stream audio data, the service enforces various timeouts. If one of these timeouts lapses, the service closes the connection.

> A session timeout (HTTP status code 408) occurs when a client starts a session but the service receives no audio for 30 seconds. It also occurs when a session is active but no request is received from the client for 30 seconds. The latter condition occurs only if the service receives no data from the client for 30 seconds and it has not yet received the last chunk of data. If the client has sent all data, the service can take more than 30 seconds to generate a response; in this case, the request does not time out.

> For both WebSocket connections and HTTP sessions, you can keep a session active by sending any audio data, including just silence, before the 30-second session timeout occurs. (You must also set the inactivity_timeout parameter to -1, as described in the next bullet.) You are charged for the duration of any data that you send to the service, including the silence that you send to extend a session.

> Ideally, you would establish a session just before you obtain audio for transcription and maintain it by sending audio at a rate that is close to real time. Your application should also recover gracefully from closed connections.

> An inactivity timeout (HTTP status code 400) occurs when the service is receiving audio from the client but it detects silence (no speech) for 30 seconds. The service uses the inactivity timeout to ensure that a session remains active. The timeout is useful, for example, for terminating a session when a user simply walks away from a live microphone.

> You can override this timeout by specifying a different value for the inactivity_timeout parameter. Specify a value of -1 to set the inactivity timeout to infinity.

[1]: https://www.ibm.com/watson/developercloud/doc/speech-to-text/input.html#timeouts
