### ISSUE TITLE
Build all frameworks with Xcode 9 / Swift 3.2

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#641]
The Xcode 9 Beta 2 release is out! Let's make sure that we can build all of our frameworks with Xcode 9 / Swift 3.2.

In particular, I ran into an issue with the Text to Speech framework and how it imports some of the Opus dependencies. We'll need to take a look and see if we can figure that out.

**Comment by glennrfisher** [comment]
For example, here's the Carthage output from @PaschalisT

```bash
*** Checking out swift-sdk at "v0.16.0"
*** Building scheme "AlchemyDataNewsV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "AlchemyLanguageV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "DialogV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "AlchemyVisionV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "ConversationV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "PersonalityInsightsV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "TextToSpeechV1" in WatsonDeveloperCloud.xcodeproj
Build Failed
Task failed with exit code 65:
/usr/bin/xcrun xcodebuild -project /Users/Paschalis/Project9/Carthage/Checkouts/swift-sdk/WatsonDeveloperCloud.xcodeproj -scheme TextToSpeechV1 -configuration Release -derivedDataPath /Users/Paschalis/Library/Caches/org.carthage.CarthageKit/DerivedData/swift-sdk/v0.16.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build (launched in /Users/Paschalis/Project9/Carthage/Checkouts/swift-sdk)
```

**Comment by h36ahmed** [comment]
Hi @glennrfisher , is there any fix for this issue? I am not using TextToSpeechV1 module but I am using SpeechToTextV1 and yet I am not able to get to it cuz it crashes here everytime.

**Comment by glennrfisher** [comment]
Unfortunately not, but I hope to carve out some time next week to fix it before the official release of Xcode 9 and iOS 11.

I think this problem cropped up with the Xcode 9 beta, so you could try using the latest version of Xcode 8 instead. Or perhaps you could set the command line tools to Xcode 8, build the SDK, then switch back to Xcode 9 for your app development.

![screen shot 2017-09-05 at 4 13 40 pm](https://user-images.githubusercontent.com/1957636/30083724-4b3669b2-9255-11e7-85f8-fc707ea16c9e.png)

**Comment by h36ahmed** [comment]
Thanks @glennrfisher for the update! Let me know when the fix is made! Meanwhile, I will have to use  Xcode 8.

**Comment by glennrfisher** [comment]
Fixed with commit a381dec61c6ebd83a655d9651fa1dd212f3f20ef included in #664.

**Comment by johnlpm** [comment]
I encounter _no such module 'CommonCrypto'
import CommonCrypto
       ^_
on running `carthage update --platform iOS`

how can i fix this?

**Comment by mkistler** [comment]
See https://github.com/daltoniam/Starscream/issues/587
