### ISSUE TITLE
Remove continuous parameter

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#642]
The `continuous` parameter was removed from Speech to Text with [the May 22 update][1]. We should remove the parameter from the `SpeechToTextSettings` object and also update the readme to include information about how to use `final` results to identify end-of-speech events and stop the request.

Here's a quick example:

> Many applications may want to stop transcribing the microphone after an end-of-speech event. To detect an end-of-speech event, set `interimResults` to `true` and watch for a `final` result. The `final` result signifies an end-of-speech event, after which you can stop the microphone.

This [comment][2] may also be helpful when modifying the readme. It includes some sample code to watch for `final` results.

[1]: https://www.ibm.com/watson/developercloud/doc/speech-to-text/release-notes.html#May2017
[2]: https://github.com/watson-developer-cloud/swift-sdk/issues/632#issuecomment-310065133

**Comment by riverbaymark** [comment]
Thanks for the work on this!

**Comment by glennrfisher** [comment]
Complete with #654.
