### ISSUE TITLE
Quickstart file under the CartFile instructions does not match the image

### ISSUE THREAD

**Issue by dsullivan2** [watson-developer-cloud/swift-sdk#650]
The text instructions has:
github "watson-developer-cloud/swift-sdk"

The image still has:
github "watson-developer-cloud/ios-sdk"

Should the "ios-sdk" be used for anything now or only "swift-sdk"?

**Comment by glennrfisher** [comment]
Good find! The SDK was renamed from "iOS SDK" to "Swift SDK". The correct setting to use is:

```
github "watson-developer-cloud/swift-sdk"
```

But `/ios-sdk` should redirect to `/swift-sdk` so it should work either way.

We'll update the image soon. Thanks for letting us know!

**Comment by glennrfisher** [comment]
Thanks again for letting us know! Just opened a PR to update the screenshot.
