### ISSUE TITLE
[speech-to-text] Get "invalid HTTP upgrade" when trying to switch to STT service in Frankfurt

### ISSUE THREAD

**Issue by troyibm** [watson-developer-cloud/swift-sdk#652]
There's no instructions on how the developer goes about setting the SpeechToText classes to use the stream-fra endpoint for services in Frankfurt, Germany.  Setting the serviceURL (even websocketsURL and tokenULR) property(ies) doesn't work for me.  I get the following error:

```error: Error Domain=WebSocket Code=403 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade}```

To reproduce, create a STT service in Germany bluemix region.
Change sample STT code to use that service.

I'm using latest swift-sdk commit  903b239
Xcode 8.3.2
iOS deployment target 9.3

**Comment by mkistler** [comment]
I got the [STT demo app](https://github.com/watson-developer-cloud/speech-to-text-swift) working with Frankfurt Bluemix.  I just followed the instructions in the README.md for the sample app and then added these lines in `AudioFileViewController.swift` in `viewDidLoad` right after instantiating the `SpeechToText` service:
```
        speechToText.serviceURL = "https://stream-fra.watsonplatform.net/speech-to-text/api"
        speechToText.tokenURL = "https://stream-fra.watsonplatform.net/authorization/api/v1/token"
        speechToText.websocketsURL = "wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize"
```

**Comment by glennrfisher** [comment]
I can confirm that @mkistler's instructions worked for me. The sample app worked after creating a Speech to Text instance in the Germany region and specifying the urls above.

After experimenting with the sample app, I did find a couple situations that produced an "Invalid HTTP upgrade" error:
- Using incorrect credentials.
- Using correct credentials, but for an instance in another region.

If you're still experiencing the same error after adding the urls above, then it would be worth verifying the region and credentials of the Speech to Text instance you're using.

Digging through the SDK, I think I found a way to produce a better error message for invalid credentials. If you're interested, check out #655 for the technical details.

**Comment by troyibm** [comment]
thanks for the comment @glennrfisher.  Are there plans to make changing the service endpoint easier and foolproof (like in java-sdk)?

I'm pretty sure I was using the correct credentials.  I just wasn't setting all three of the URLs.  It didn't make sense to me to change the tokenURL since I wasn't using tokens.

We need to make this more seamless in the SDK.  I've been adding to all my apps the ability to switch between bluemix regions since they are used all over the world.  The hack I've come up with is code like this...
```swift
    static let bluemixRegions = [
        "US South",
        "United Kingdom",
        "Germany",
        "Sydney",
    ]
    static let sttEndpoints : [String: String] = [
        bluemixRegions[0]: "stream.watsonplatform.net",
        bluemixRegions[1]: "stream.watsonplatform.net",
        bluemixRegions[2]: "stream-fra.watsonplatform.net",
        bluemixRegions[3]: "stream.watsonplatform.net",
        ]
    init(region: String, speechModel: String?, resultsHandler: STTResultsHandler) {
        self.speechToText = SpeechToText(username: (WatsonSTT.speechToTextMap[region]?[0])!,
                                        password: (WatsonSTT.speechToTextMap[region]?[1])!)
        self.speechToText.serviceURL = "https://" + WatsonSTT.sttEndpoints[region]! + "/speech-to-text/api"
        self.speechToText.tokenURL = "https://" + WatsonSTT.sttEndpoints[region]! + "/authorization/api/v1/token"
        self.speechToText.websocketsURL = "wss://" + WatsonSTT.sttEndpoints[region]! + "/speech-to-text/api/v1/recognize"
    }
```

**Comment by glennrfisher** [comment]
That's a great suggestion, @troyibm. I opened #658 to track that issue.

We have some documentation about [custom service urls][1] in the readme, but it's not very descriptive and doesn't mention the `tokenURL` field for Speech to Text. I also opened #657 so we can improve the documentation when we have a chance.

For now, you might want to consider using enumerations instead of dictionaries. I personally find it a bit cleaner because it groups the relevant data together and removes those pesky optionals.

```swift
enum Region {
    case unitedStatesSouth
    case unitedKingdom
    case germany
    case sydney

    var endpoint: String {
        switch self {
        case .unitedStatesSouth: return "stream.watsonplatform.net"
        case .unitedKingdom: return "stream.watsonplatform.net"
        case .germany: return "stream-fra.watsonplatform.net"
        case .sydney: return "stream.watsonplatform.net"
        }
    }

    var username: String {
        switch self {
        case .unitedStatesSouth: return "your-username-here"
        // ...
        }
    }

    var password: String {
        switch self {
        case .unitedStatesSouth: return "your-username-here"
        // ...
        }
    }
}

init(region: Region, model: String, handler: STTResultsHandler) {
    speechToText = SpeechToText(username: region.username, password: region.password)
    speechToText.serviceURL = "https://" + region.endpoint + "/speech-to-text/api"
    speechToText.tokenURL = "https://" + region.endpoint + "/authorization/api/v1/token"
    speechToText.websocketsURL = "wss://" + region.endpoint + "/speech-to-text/api/v1/recognize"
}
```

[1]: https://github.com/watson-developer-cloud/swift-sdk#custom-service-urls
