### ISSUE TITLE
Improve documentation for service and token urls

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#657]
The readme currently contains some information on setting a custom service url, but it is relatively sparse. We should improve the documentation, and include information about the token url for Speech to Text and other token-based services.

**Comment by mkistler** [comment]
Documentation for the service URL has been standardized across the SDKs and is now included in the README. All other URLs (e.g. the STT token URL) are internally derived from the base service URL, so these do not require any documentation.
