### ISSUE TITLE
Add helper function to change endpoint

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#658]
The SDK currently exposes public properties for the `serviceURL` (and `tokenURL` and `websocketsURL` for some services, like Speech to Text). Consider using a helper function instead, so that clients only need to specify the endpoint once, rather than specifying the full url several times.

For example, see the [setEndPoint][1] function in the Java SDK.

[1]: https://github.com/watson-developer-cloud/java-sdk/blob/develop/core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java#L341

**Comment by mkistler** [comment]
The feature was implemented in [Release 1.0](https://github.com/watson-developer-cloud/swift-sdk/releases/tag/1.0.0).
