### ISSUE TITLE
[text-to-speech] Module fails to be build via carthage in Swift 3.2

### ISSUE THREAD

**Issue by PaschalisT** [watson-developer-cloud/swift-sdk#662]
Just by doing a clean: carthage update --platform ios --no-use-binaries

Output of watson swift-sdk:

*** Checking out swift-sdk at "v0.16.0"
*** Building scheme "AlchemyDataNewsV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "AlchemyLanguageV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "DialogV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "AlchemyVisionV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "ConversationV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "PersonalityInsightsV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "TextToSpeechV1" in WatsonDeveloperCloud.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/Paschalis/Project9/Carthage/Checkouts/swift-sdk/WatsonDeveloperCloud.xcodeproj -scheme TextToSpeechV1 -configuration Release -derivedDataPath /Users/Paschalis/Library/Caches/org.carthage.CarthageKit/DerivedData/swift-sdk/v0.16.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build (launched in /Users/Paschalis/Project9/Carthage/Checkouts/swift-sdk)

Xcode version 9 (beta)

Rest of the modules appear to be unaffected and could be build without issues.

**Comment by glennrfisher** [comment]
Thanks for the note, @PaschalisT!

I'm going to copy your output into #641 then close this issue in favor of that one. Hoping to carve out some time next week to fix this problem before Xcode 9 is officially released.
