### ISSUE TITLE
[conversation] Mutable Context json

### ISSUE THREAD

**Issue by bfaist** [watson-developer-cloud/swift-sdk#665]
https://github.com/watson-developer-cloud/swift-sdk/blob/70eb51ceaca286c8467a34de473d350a167597f4/Source/ConversationV1/Models/Context.swift#L24

Any chance for "json" to be mutable instead of immutable? (var vs let)

The context variables in the Conversation workspace could be set/updated based on some logic in the phone app and then sent in the next message request to the Conversation service.

The work-around is to copy the Context json to a Dictionary, modify the dictionary, and create a whole new Context object based on the modified dictionary.  Then continue the conversation with the new Context.

**Comment by glennrfisher** [comment]
Hi @bfaist. I'll be taking a look at this over the next week or two. We definitely want to find a better way to support these additional properties.

This issue is similar to #620, so I'm going to close this particular issue and continue the conversation over there.
