### ISSUE TITLE
Publish to CocoaPods

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#668]
- [ ] Publish the SDK to CocoaPods
- [ ] Add additional maintainers (e.g. @vherrin, @mkistler)
- [ ] Update documentation to reference CocoaPods installation

**Comment by igor9silva** [comment]
+1 for that

**Comment by kimdv** [comment]
+1

**Comment by papanton** [comment]
+1

**Comment by svmadiraju** [comment]
+1

**Comment by Shoshin23** [comment]
+1 for that.

**Comment by RodolfoAntonici** [comment]
+1

**Comment by sihekuang** [comment]
+1

**Comment by AnthonyOliveri** [comment]
Sorry for the delay everyone. I'm currently working on this, so Cocoapods will be supported in the near future 🙂

**Comment by AnthonyOliveri** [comment]
Cocoapods is now supported as of version 0.33.0!
