### ISSUE TITLE
Get and post a context variable when starting conversation ?

### ISSUE THREAD

**Issue by WestFR** [watson-developer-cloud/swift-sdk#676]
Hello everyone,

I defined a context variable "lang" in my dialogs to specify the language of the response.
I would like to enter this variable in my application when I initiate my conversation.

With the following code, the lang variable is equal to nil.
How to do it ?

`
func startConversation() 
{
        conversation.message(withWorkspace: workspace,failure: failure)
        {
            response in
            self.context = response.context
            let lang = response.context.json["lang"] as? String
            print(lang) // is nil
            print(self.context) // doesn't contains lang context variable
        }
`

Moreover, when I send a message, I would like to re-enter this context variable "lang", how to do it ?

I searched on this repository for issues related to this issue but I did not find an implementation that works in my case.

Thank you very much for your help!

**Comment by glennrfisher** [comment]
Hi @WestFR. You're right, that we haven't had a good way to set context variables. Sorry for the trouble!

We've been working on updates to the Conversation service, including a better way to get/set these context variables. I opened a pull request (#680) that should make this much easier.

To keep things organized, I'm going to close this issue in favor of #620. But I'll post an example with the new changes over there. I would love to get your opinion, and whether you like or dislike the new support for setting context variables! Thanks!
