### ISSUE TITLE
Refresh token of SpeechToText

### ISSUE THREAD

**Issue by jofujimoto** [watson-developer-cloud/swift-sdk#681]
I would like to use SpeechToText for a long time. Therefore, it is necessary to refresh the token many times. However, the current SDK will only be done once. ([maxTokenRefreshes] of SpeechToTextSocket.swift is private variable) 
Is there a way to change this number?

(In the phenomenon occurring, "Invalid HTTP upgrade" error occurs about 1 hour later.)

**Comment by glennrfisher** [comment]
@jofujimoto I think this should work as expected. The `tokenRefreshes` property is reset to `0` after a connection is established. Here's the [line of code][1].

You might want to consider setting the [`inactivityTimeout`][2] to keep the connection alive.

[1]: https://github.com/watson-developer-cloud/swift-sdk/blob/master/Source/SpeechToTextV1/SpeechToTextSocket.swift#L220
[2]: https://github.com/watson-developer-cloud/swift-sdk/blob/master/Source/SpeechToTextV1/Models/RecognitionSettings.swift#L38
