### ISSUE TITLE
 Watson Visualrecognizition SDK is broken in xcode 9 (Starterkeit)

### ISSUE THREAD

**Issue by vinapp** [watson-developer-cloud/swift-sdk#691]
Watson Visualrecognizition starterkit is broken in xcode 9

https://console.bluemix.net/developer/mobile

Error:
Module compiled with Swift 3.1 cannot be imported in Swift 3.2: /Users/..../Carthage/Build/iOS/VisualRecognitionV3.framework/Modules/VisualRecognitionV3.swiftmodule/x86_64.swiftmodule

**Note:**

In the starterkit we need to support both… How do we go about ? not every one would have moved to xcode 9 in order for it to make work for xcode 9 what is the pod entries I need to put ?

**Comment by glennrfisher** [comment]
Hi Vinod. I tried out different versions of the Watson Swift SDK with various versions of Xcode.

**In short, you can use `v0.17.0` if you need to maintain Xcode 8 compatibility. But it will not contain newer bug fixes, enhancements, and features.**

Version `v0.17.0` of the Swift SDK was before the migration to Swift 4, while version `v0.19.0` was after the migration and includes several new bug fixes and enhancements.

| Swift SDK | Xcode | Result | Description |
| - | - | - | - |
| v0.19.0 | 9.1 | ✅ | Carthage reported, "incompatible Swift version - framework was built with 4.0 and the local version if 4.0.2." Carthage skipped the binary and built from source. Although it took a long time to build from source, it worked just fine in an iOS app. |
| v0.19.0 | 9.0.1 | ✅ | Carthage used the binary download. No build errors or warnings in Xcode. Worked as expected. |
| v0.19.0 | 8.3.3 | ❌ | Carthage reported, "incompatible Swift version - framework was built with 4.0 and the local version if 3.1." Carthage skipped the binary and tried to build from source, but failed with the error "'Swift Language Version' is required to be configured correctly for targets which use Swift." In other words, Xcode 8.3.3 did not recognize the Swift 4 configuration. |
| v0.17.0 | 9.1 | ✅ | Carthage reported, "incompatible Swift version - framework was built with 3.1 and the local version if 4.0.2." Carthage skipped the binary and built from source. Although it took a long time to build from source, it worked just fine in an iOS app. |
| v0.17.0 | 9.0.1 | ✅ | Carthage reported, "incompatible Swift version - framework was built with 3.1 and the local version if 4.0." Carthage skipped the binary and built from source. Although it took a long time to build from source, it worked just fine in an iOS app. |
| v0.17.0 | 8.3.3 | ✅ | Carthage used the binary download. No build errors or warnings in Xcode. Worked as expected. |

**Comment by vinapp** [comment]
Hi Gleen, I still get the below error :Module compiled with Swift 3.1 cannot be imported in Swift 3.2: /Users/..../Carthage/Build/iOS/VisualRecognitionV3.framework/Modules/VisualRecognitionV3.swiftmodule/x86_64.swiftmodule

**Comment by vinapp** [comment]
sorry, it works :+1: my swift version was pointing to 3.1

**Comment by vinapp** [comment]
thanks for quickly resolving this.

**Comment by cmcgheit** [comment]
I am still currently having this problem on Xcode 8.3.3 with the Watson Conversation framework:

I carthage boostrap to v0.17.0 and am still seeing the "Module complied with Swift 4.0 cannot be imported with Swift 3.1" error when I try to run the project.

![screen shot 2017-11-29 at 9 33 49 pm](https://user-images.githubusercontent.com/24944725/33441814-33419f8c-d5b9-11e7-8f4f-56893d587b9d.png)

I have deleted the entire Watson framework and readded with carthage/manually and I still get this error?

**Comment by glennrfisher** [comment]
Hi @cmcgheit. Your command-line version of Swift may not align with the version of Xcode that you are using to develop your application. Can you try the following?

1. Delete the `Carthage` directory in your application to remove the existing frameworks built with Swift 4.0.

2. Set the command-line-tools in your Xcode preferences to match the version of Xcode that you are using to develop your app (for Swift 3.1, you are probably using Xcode 8.3). I've included a screenshot below in case that's helpful.

3. Run `carthage update --platform iOS` again.

![image](https://user-images.githubusercontent.com/1957636/33449343-184fb5e6-d5ce-11e7-9789-c18a24d2e402.png)

**Comment by cmcgheit** [comment]
Thanks for the reply. Should I use the v0.19.0 carthage build or v0.17.0? Also, wouldn't running carthage update --platform iOS automatically upgrade to v0.19.0, thus making it unusable with Xcode 8.3.3?

**Comment by glennrfisher** [comment]
Hi @cmcgheit. You can specify a [version requirement][1] in your `Cartfile` to choose a particular version of the Watson SDK for your application.

For example, if you want to use the v0.17.0 version, you would specify the following in the `Cartfile`:

```
github "watson-developer-cloud/swift-sdk" == 0.17.0
```

The particular version to use depends on your application requirements and the version of Xcode you are using. For Xcode 8.3.3 (Swift 3.1), which you mentioned in your earlier comment, you will want to specify version `0.17.0`.

[1]: https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#version-requirement

**Comment by cmcgheit** [comment]
Thanks a lot Glenn! That did it!
