### ISSUE TITLE
Parse JSON of custom response with new version of package

### ISSUE THREAD

**Issue by WestFR** [watson-developer-cloud/swift-sdk#692]
Hello everyone,

For a week, I updated your swift-SDK to match my application with your technology and I develop a version on my application with IBM Watson.

Prior to this update, I analyzed the custom JSON response on my dialog box and it worked fine until the update.

Now I can not parse the JSON response returned by the system because it returns a complex architecture.

You will find my old and new code used below.

<img width="1112" alt="capture d ecran 2017-11-16 a 09 46 10" src="https://user-images.githubusercontent.com/21226632/32881927-0c488744-cab3-11e7-92fd-2b7d727258b0.png">

**Comment by glennrfisher** [comment]
Hi @WestFR,

Sorry for the delayed response, I've been on vacation for the Thanksgiving holiday.

The new approach to JSON parsing published with v0.19.0 should be more robust and type-safe than the previous implementations. But I can understand your frustration with the change.

Let me provide an example that may help.

Let's assume that the message response from the service includes the following JSON values.

```json
{
  "context": {
    "custom-string": "this is a string",
    "custom-array": [1, 2, 3],
    "custom-object": { "x": 1 }
  }
}
```

Then these additional properties can be parsed with the following Swift code.

```swift
conversation.message(workspaceID: workspaceID, request: request, failure: failure) {
    response in
    let additionalProperties = response.context.additionalProperties
    guard case let .string(customString) = additionalProperties["custom-string"]! else { return }
    guard case let .array(customArray) = additionalProperties["custom-array"]! else { return }
    guard case let .int(customArray0) = customArray[0] else { return }
    guard case let .int(customArray1) = customArray[1] else { return }
    guard case let .int(customArray2) = customArray[2] else { return }
    guard case let .object(customObject) = additionalProperties["custom-object"]! else { return }
    guard case let .int(x) = customObject["x"]! else { return }
}
```

Hope that helps!
