### ISSUE TITLE
Tone Analyzer service not parsing JSON for "tone_categories" properly 

### ISSUE THREAD

**Issue by agarc657** [watson-developer-cloud/swift-sdk#694]
[tone-analyzer] rest kit not parsing returning json properly 

Example used 
`import ToneAnalyzer

let username = "your-username-here"
let password = "your-password-here"
let version = "YYYY-MM-DD" // use today's date for the most recent version
let toneAnalyzer = ToneAnalyzer(username: username, password: password, version: version)

let text = "I was asked to sign a third party contract a week out from stay. If it wasn't an 8 person group that took a lot of wrangling I would have cancelled the booking straight away. Bathrooms - there are no stand alone bathrooms. Please consider this - you have to clear out the main bedroom to use that bathroom. Other option is you walk through a different bedroom to get to its en-suite. Signs all over the apartment - there are signs everywhere - some helpful - some telling you rules. Perhaps some people like this but It negatively affected our enjoyment of the accommodation. Stairs - lots of them - some had slightly bending wood which caused a minor injury."
let failure = { (error: RestError) in print(error) }

toneAnalyzer.getTone(text, failure: failure) { tones in
		// code here
}`

Expected result:

should have found keys 

Actual Result 

keyNotFound("tone_categories")

This is the latest version that i am using 
target device is iPhone 8 IOS 11.1

After downloading the Rest Kit and stepping through the code I believe the issue is within the the Parsing for the JSON returned. the API call is returning the correct JSON but the Parsing is erroring out and returning no keys found. I believe it has to do with the nesting of the dictionary but I am unsure.

**Comment by glennrfisher** [comment]
I'm afraid you ran into a bug with the Swift SDK! It looks like the 2017-09-25 release of the Tone Analyzer service removed the `tone_categories` key, which causes the SDK's JSON parsing to fail. Thanks for letting me know. I'll work on a fix soon.

In the meantime, a quick fix is to set the version date earlier. For example, you could set it to the previous release of 2017-07-06.

Here is a [sample app][1] for Tone Analyzer that I was able to test and run successfully.

Hope that helps!

[1]: https://github.com/watson-developer-cloud/swift-sdk/files/1519229/ToneAnalyzer.zip

**Comment by glennrfisher** [comment]
I'm going to close this issue in favor of #695, which we'll use to track the update of the Tone Analyzer code for the 2017-09-25 release.

In the mean time, please use a version date prior to 2017-07-06 and let me know if you run into any more trouble!
