### ISSUE TITLE
How to store word timestamp in ios + swift ? beacause i have no idea . suggest me some sample code for that

### ISSUE THREAD

**Issue by sunil28011** [watson-developer-cloud/swift-sdk#734]

**Comment by glennrfisher** [comment]
Hi @sunil28011. I don't fully understand your question. But I think you're asking how to retrieve a word's start and end timestamps when using Speech to Text. If that's not what you're looking for then feel free to leave another comment to explain.

First, let me point you to this [WordTimestamp documentation][1] that describes the properties on a `WordTimestamp`. You may find it helpful.

Here is some example code that prints the start/end times for each word in a transcription.

```swift
// define settings for recognition request
var settings = RecognitionSettings(contentType: format)
settings.timestamps = true

// send audio for recognition request
speechToText.recognize(audio: file, settings: settings, failure: failWithError) { results in

    // extract timestamps from the response and print them
    if let timestamps = results.results.last?.alternatives.last?.timestamps {
        for timestamp in timestamps {
            print("\(timestamp.word): \(timestamp.startTime) - \(timestamp.endTime)")
        }
    }
}
```
Here is an example of the printed output when I ran that code on a WAV file.
```
several: 1.0 - 1.52
tornadoes: 1.52 - 2.15
touch: 2.15 - 2.49
down: 2.49 - 2.82
as: 2.82 - 2.92
a: 2.92 - 3.01
line: 3.01 - 3.3
of: 3.3 - 3.39
severe: 3.39 - 3.77
thunderstorms: 3.77 - 4.51
swept: 4.51 - 4.79
through: 4.79 - 4.95
Colorado: 4.95 - 5.59
on: 5.59 - 5.73
Sunday: 5.73 - 6.35
```

[1]: http://watson-developer-cloud.github.io/swift-sdk/swift-api/services/SpeechToTextV1/Structs/WordTimestamp.html#/s:14SpeechToTextV113WordTimestampV9startTimeSdv
