### ISSUE TITLE
Module compiled with Swift 4.0.3 error in Xcode 9.2

### ISSUE THREAD

**Issue by xyzbilal** [watson-developer-cloud/swift-sdk#736]
looking forward for new updates..

**Comment by glennrfisher** [comment]
Hi @xyzbilal. I just tested the latest release again and had no issues with Xcode 9.2. Perhaps you're running a different version?

It would be helpful to double-check that you're running `Version 9.2 (9C40b)` and that your command line tools (Xcode Preferences -> Locations -> Command Line Tools) is also set to `Xcode 9.2 (9C40b)`.

If you continue to run into problems, you can always use Carthage to rebuild the SDK using the version of Swift that you have specified with the command line tools: `carthage update --platform iOS --no-use-binaries`.

Hope that helps. Let us know if you run into any other problems.
