### ISSUE TITLE
WTF? API removed for public func LanguageTranslatorV2.translate using from and to

### ISSUE THREAD

**Issue by csantanapr** [watson-developer-cloud/swift-sdk#774]
It looks like the func `translate` using `from:` and `to:` was removed.
https://github.com/watson-developer-cloud/swift-sdk/commit/1660f5c60770da750d8b6dc57d4babbe70c478ea#diff-1cbc7b0e22563833516d26f44d49b728L322

This is kind of braking change API for end users.

It looks like there is a new API for translate where a new TranslateRequest needs to be use. I figure this out from reading the source code not the README.

The README has the old API in it
```
let failure = { (error: Error) in print(error) }
languageTranslator.translate("Hello", from: "en", to: "es", failure: failure) {
    translation in
    print(translation)
}
```

I think you should consider as a migration and backwards compatibility to add back the public method signature, as an interface and call the new API under the covers to not brake peoples apps in the field.

**Comment by germanattanasio** [comment]
Hi @csantanapr, you raised some good points here. We are switching to generate the SDK from the Swagger specification and that probably changed the signature for some of the method like `translate()`.

@glennrfisher do you think we can plan to update the README and add a MIGRATION guide for users using the previous version of the SDK?

**Comment by germanattanasio** [comment]
Regarding the backward compatibility. I guess you know the SDK version is still less than 1.0. Therefore, we don't need to maintain backward compatibility.

This is specified in https://semver.org/:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I agree it's not a great experience for users, but it's always a tradeoff between resources and business goals.

**Comment by glennrfisher** [comment]
Hi @csantanapr. Thanks for pointing this out. I updated the readme to reflect the API changes that were made with the v0.22.0 release.

I agree that we should try to avoid breaking changes. We're pushing hard to publish a stable, mature, long-term release of the Swift SDK as a v1.0 release. After that major release, we plan to go to great lengths to maintain backwards compatibility.

Unfortunately, we need to make some changes on the way to our v1.0 release. One of those, as @germanattanasio mentioned, is to generate the Swift SDK from Swagger specifications. With our small team, that's our best bet to keep the SDK up-to-date as services evolve. But many of the constructs we have handwritten in the past cannot be generated. So we are in the process of updating the SDK to the generated API.

There are still more changes to come with Discovery and Speech to Text. There may also be some fundamental changes to correct early decisions now that the Swift community is more mature—for example, we will probably migrate away from the Objective-C pattern of separate failure and success blocks to the Swifty pattern of a single completion handler.

Thanks for sticking with us on the ride. And we're sorry for the bumps along the way!

**Comment by csantanapr** [comment]
@germanattanasio 
>Regarding the backward compatibility. I guess you know the SDK version is still less than 1.0. Therefore, we don't need to maintain backward compatibility.

Glad to hear you were able to get away not having a stable API since [first commit 2015](https://github.com/watson-developer-cloud/swift-sdk/commit/e6d0ad558c7890695edf57c680c4b080794df3db)
3 years without a commitment on a stable API, 

I think is great that work is ongoing to finally have a 1.x after 3 years.

I hope no one was using this SDK in real enterprise production systems, since it was 0.x

So for 1.x your going to follow semver then? Any API break your going to branch to 2.x and son on?

**Comment by csantanapr** [comment]
@glennrfisher 

Thanks for the update, is there an issue open discussing and keeping users up to date on this upcoming changes?

You would not believe how many folks will appreciate an issue just discussing the upcoming changes and plans, and asking for feedback on these changes.

>for example, we will probably migrate away from the Objective-C pattern of separate failure and success blocks to the Swifty pattern of a single completion handler.

This makes a lot of sense 👍 it will align with what I'm working with @seabaylea in Codable routing and Codable Serverless

Would the responses for the APIs in addition of completion handler they would also be Codable to easier JSON manipulation?

Here is what a Serverless Function using Codable completion handler looks like
https://github.com/ibm-functions/runtime-swift/blob/master/tests/dat/actions/integration/testWatsonActionCodable.swift
```swift 
struct Input: Codable {
    let username: String
    let password: String
    let url: String?
}
struct Output: Codable {
    let translation: String
}
func main(param: Input, completion: @escaping (Output?, Error?) -> Void) -> Void {
    let languageTranslator = LanguageTranslator(username: param.username , password: param.password)
    let request = TranslateRequest(text: ["Hello"], source: "en", target: "es")
    let failure = {(error: Error) in
        completion(nil, error)
    }
    let _ = languageTranslator.translate(
       request: request,
       failure: failure) {translation in
        let result = Output(translation: translation.translations.first?.translationOutput as! String)
        completion(result, nil)
    }
}
```
