### ISSUE TITLE
Swift 4.1 SDK update Issue

### ISSUE THREAD

**Issue by ramg7** [watson-developer-cloud/swift-sdk#782]
When I update the sdk I get the following error: 

*** Downloading swift-sdk.framework binary at "v0.23.2"
*** Skipped installing swift-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."

Is there any way this can be solved or the update will be coming up soon?

Sincerely,
Roberto 👍

**Comment by glennrfisher** [comment]
Hi @ramg7. Absolutely! We're working on a new release for Swift 4.1 / Xcode 9.3. Hope to have it out later today or tomorrow.

(For more information about this particular issue, check out this [duplicate issue](https://github.com/watson-developer-cloud/swift-sdk/issues/780#issuecomment-377947105).)

**Comment by ramg7** [comment]
Thank you Glenn! You guys are the best! 💯 @glennrfisher

**Comment by glennrfisher** [comment]
Quick update: this problem should be fixed now with [v0.23.3][1].

[1]: https://github.com/watson-developer-cloud/swift-sdk/releases/tag/v0.23.3
