### ISSUE TITLE
GitHub API request failed: networkError(Error Domain=NSURLErrorDomain Code=-1200

### ISSUE THREAD

**Issue by yuandonghua** [watson-developer-cloud/swift-sdk#783]
Skipped installing swift-sdk.framework binary due to the error:
	"GitHub API request failed: networkError(Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9802, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x7fcdbd54e650 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://github-production-release-asset-2e65be.s3.amazonaws.com/42934262/ed8c2aa8-32a0-11e8-8bfc-70a155ac3226?X

**Comment by glennrfisher** [comment]
Hmm, I've never seen this before. Unfortunately, there's not much we can do--the problem either lies with GitHub, your ISP, or your machine configuration. Maybe you're operating through a proxy that messes with SSL?

**Comment by yuandonghua** [comment]
The solution to this problem is to update the ssh of the GitHub account in xcode.
