### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by yuandonghua** [watson-developer-cloud/swift-sdk#785]
yuandonghuadeiMac:visual-recognition-coreml yuandonghua$ carthage update --platform iOS
*** Fetching swift-sdk
*** Checking out Starscream at "31f522155a4d6323cd1aaefb8dbc140ced7be1ca"
*** Checking out swift-sdk at "v0.23.3"
*** xcodebuild output can be found in /var/folders/r9/thfhsnx11zxg57_xwmz_mfnr0000gn/T/carthage-xcodebuild.IYle32.log
*** Skipped downloading Starscream.framework binary due to the error:
	"Bad credentials"
*** Skipped downloading swift-sdk.framework binary due to the error:
	"Bad credentials"
*** Building scheme "Starscream" in Starscream.xcodeproj

**Comment by yuandonghua** [comment]
GitHub API request failed: networkError(Error Domain=NSURLErrorDomain Code=-1200,
After solving this problem, there have been new issues

**Comment by glennrfisher** [comment]
Hi @yuandonghua. Something is funky with your `git` configuration. Seems like it's trying to connect to GitHub with the wrong credentials. This [issue][1] might be helpful.

[1]: https://github.com/Carthage/Carthage/issues/1188
