### ISSUE TITLE
macOS platform not supported

### ISSUE THREAD

**Issue by pedrobusko** [watson-developer-cloud/swift-sdk#823]
carthage bootstrap --platform osx

we got this error: "Dependency "swift-sdk" has no shared framework schemes for any of the platforms: Mac".

We are using Visual Recognition, so we add this folder https://github.com/watson-developer-cloud/swift-sdk/tree/master/Source/VisualRecognitionV3 directly into the project. But it is using UIImage which is for iOS, so we changed that to NSImage for macOS. After that it worked.

**Comment by germanattanasio** [comment]
@ShihabMehboob do you think you can take a look at this and estimate it? Thanks

**Comment by ShihabMehboob** [comment]
@pedrobusko I see that you replaced macOS specific elements to their iOS counterparts, does this now work properly for you or is the issue still there?

**Comment by pedrobusko** [comment]
@ShihabMebboob it worked for us. Adding the folder manually to the xcode project and replacing UIImage witn NSImage.

**Comment by mkistler** [comment]
Uses of `UIImage` in the SDK are in the file `VisualRecognition+UIImage.swift`, and all the code in this file is ifdefed for just iOS, WatchOS, and tvOS:

https://github.com/watson-developer-cloud/swift-sdk/blob/master/Source/VisualRecognitionV3/VisualRecognition%2BUIImage.swift#L17
