### ISSUE TITLE
[visual-recognition] listClassifiers isn't working

### ISSUE THREAD

**Issue by bourdakos1** [watson-developer-cloud/swift-sdk#833]
When running listClassifiers I get the following error: 
```
keyNotFound(CodingKeys(stringValue: "core_ml_enabled", intValue: nil),
Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "classifiers", intValue: nil),
_JSONKey(stringValue: "Index 0", intValue: 0)],
debugDescription: "No value associated with key CodingKeys(stringValue: \"core_ml_enabled\", intValue: nil) (\"core_ml_enabled\").", underlyingError: nil))
```
I have classifiers that should be able to be listed and this worked for me in the past. I assume it is because of the new "core_ml_enabled" key in the json response. 

I'm running Xcode version 9.3
Watson Swift SDK version 0.27.0
Targeting iOS 11.0

**Comment by mkistler** [comment]
Fixed in v0.28.0
