### ISSUE TITLE
Speech-To-Text to support Mac OSX?

### ISSUE THREAD

**Issue by busywq** [watson-developer-cloud/swift-sdk#856]
Is there any plan to support Mac OSX? Now I'm tring to find a solution of STT for Mac OSX app, but seems only IOS is supportted now.

**Comment by AnthonyOliveri** [comment]
Hi @busywq. We do intend to add support for macOS in the future, but we don't yet have a timeline for when it will be implemented. Our goal is to have macOS supported by the 1.0 release.

**Comment by AnthonyOliveri** [comment]
This thread may help to see if you can get STT working for macOS in the meantime: https://github.com/watson-developer-cloud/swift-sdk/issues/129.

**Comment by mkistler** [comment]
Duplicate of #129
