### ISSUE TITLE
XCode10 and Swift 4.2 support?

### ISSUE THREAD

**Issue by jacobo360** [watson-developer-cloud/swift-sdk#859]
Hi,

I installed Watson via Carthage on a project in XCode 10's demo. But since it was compiled on Swift 4.1.2 it won't allow me to import any of the frameworks in Swift 4.2.

Will there be an update soon, or is there a practical way to fix this in the meantime?

Have in mind that I need to use Swift 4.2 in my project since I plan on using ARKit2.

Thanks.

**Comment by bourdakos1** [comment]
Does Carthage fail to build it? Or it just won’t let you import it?

**Comment by jacobo360** [comment]
Carthage builds it correctly, but XCode fails to import it.

**Comment by bourdakos1** [comment]
Okay, you might be pointing to an older version of Xcodes build tools. When I use Xcode 10s build tools Carthage fails to build the project for me.

(You can check in Xcode > preferences > locations > command line tools)

A quick work around for now is inside the Carthage folder, instead of pulling the framework from the build folder, open the project found in the checkouts folder. Try to build the project with the scheme of the particular framework you want to use selected. It will probably ask if you want to update the code to Swift 4.2, say yes.

After that I saw an error about an immutable variable, just change it from let to var. After that you should be able to add that framework to your project.

Let me know if you need any help :)

Hopefully these issues will be resolved by the time Xcode 10 is out of beta

**Comment by bourdakos1** [comment]
Tracking SDK update in this issue
watson-developer-cloud/swift-sdk#841

**Comment by bourdakos1** [comment]
@mkistler 
In `VisualRecognition+CoreML.swift` I changed:
`let compiledModelTemporaryURL: URL`
to:
`var compiledModelTemporaryURL: URL`
to silence this error:
`Immutable value 'compiledModelTemporaryURL' must not be passed inout`
raised here:
`defer { try? fileManager.removeItem(at: compiledModelTemporaryURL) }`

**Comment by mkistler** [comment]
@bourdakos1 I've made this change in the v0.31 release candidate, branch `v0.31`.  Could you give that a try to see if it resolves the problem?

**Comment by bourdakos1** [comment]
@mkistler Looks like it's working now 👍

**Comment by jpmmtrader** [comment]
I upgraded my iPhone to iOS 12 and now can't compile with Xcode 9.4.1. When I moved to Xcode 10 I can't get the AssistantV1 to recompile to Swift 4.2 using --no-use-binaries

Although there maybe workarounds the ideal situation would be to have the SDK at 4.2

Here is the last part of the error log

> 
Linting 'SegmentSettings.swift' (85/115)
Linting 'MetricAggregationResult.swift' (86/115)
Linting 'CredentialDetails.swift' (87/115)
Linting 'SourceStatus.swift' (88/115)
Linting 'NluEnrichmentEmotion.swift' (89/115)
Linting 'Timeslice.swift' (90/115)
Linting 'TrainingExampleList.swift' (91/115)
Linting 'QueryResultMetadata.swift' (92/115)
Linting 'TrainingExamplePatch.swift' (93/115)
Linting 'AggregationResult.swift' (94/115)
Linting 'QueryRelationsArgument.swift' (95/115)
Linting 'TrainingStatus.swift' (96/115)
Linting 'FontSetting.swift' (97/115)
Linting 'DeleteConfigurationResponse.swift' (98/115)
Linting 'SourceOptions.swift' (99/115)
Linting 'Filter.swift' (100/115)
Linting 'Term.swift' (101/115)
Linting 'UpdateEnvironmentRequest.swift' (102/115)
Linting 'NewTrainingQuery.swift' (103/115)
Linting 'WordHeadingDetection.swift' (104/115)
Linting 'NluEnrichmentKeywords.swift' (105/115)
Linting 'LogQueryResponse.swift' (106/115)
Linting 'NluEnrichmentSentiment.swift' (107/115)
Linting 'QueryPassages.swift' (108/115)
Linting 'QueryEntitiesEntity.swift' (109/115)
Linting 'TopHits.swift' (110/115)
Linting 'DiskUsage.swift' (111/115)
Linting 'QueryRelationsFilter.swift' (112/115)
Linting 'NluEnrichmentSemanticRoles.swift' (113/115)
Linting 'NluEnrichmentFeatures.swift' (114/115)
Linting 'HtmlSettings.swift' (115/115)
Done linting! Found 12 violations, 12 serious in 115 files.

** ARCHIVE FAILED **


The following build commands failed:
PhaseScriptExecution Run\ SwiftLint /Users/XXXXXX/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/swift-sdk/0.34.0/Build/Intermediates.noindex/ArchiveIntermediates/DiscoveryV1/IntermediateBuildFilesPath/WatsonDeveloperCloud.build/Release-iphoneos/DiscoveryV1.build/Script-CAEC7A691FE984BE002EF4FD.sh
(1 failure)
>

**Comment by jpmmtrader** [comment]
I have since been able to convert the frameworks in this project to 4.2, so it's all clean now

**Comment by ZaidPathan** [comment]
Any updates on this?

**Comment by ZaidPathan** [comment]
I was able to temporarily fix this issue by removing pod **AssistantV1** from carthage and adding following to **Podfile** 
`pod 'IBMWatsonAssistantV1', '~> 0.35.0'`

And by replacing `import AssistantV1` with `import Assistant`.

**Comment by AnthonyOliveri** [comment]
@ZaidPathan Did you successfully incorporate any other services besides **AssistantV1** using Carthage?

All services should build successfully if you installed using the Carthage flag `--no-use-binaries`.

**Comment by AnthonyOliveri** [comment]
Xcode 10 and Swift 4.2 are fully supported as of version 0.38.0.
