### ISSUE TITLE
[assistant] Context Codable issue

### ISSUE THREAD

**Issue by vrisch** [watson-developer-cloud/swift-sdk#862]
We have a Kitura app that talks to the Assistant Service and as part of restoring the conversation between calls we encode/decode the Context using standard Swift JSONEncoder/JSONDecoder. Running locally on a Development Mac this runs fine, but when deploying to the IBM Cloud, decoding fails.

We use the following extension on Context:

extension Context {
    static func decode(string: String) throws -> Context? {
        guard let data = string.data(using: .utf8) else { return nil }
        Log.debug("Context.decode: decoding '\(string)'")
        do {
            let context = try JSONDecoder().decode(Context.self, from: data)
            Log.debug("Context.decode: Sucessful '\(context)")
            return context
        } catch let error {
            Log.error("Context.decode: Failed '\(error)")
            throw error
        }
    }
    func encode() throws -> String? {
        let data = try JSONEncoder().encode(self)
        let string = String(data: data, encoding: .utf8)
        Log.debug("Context.encode: Sucessful '\(string ?? "<empty>")'")
        return string
    }
}

And decode fails with:

[DEBUG] [xxx.swift:44 decode(string:)] Context.decode: decoding '{"conversation_id":"<uuid-redacted>,"system":{"_node_output_map":{"Welcome":{"0":[0]}},"dialog_request_counter":1,"dialog_stack":[{"dialog_node":"root"}],"branch_exited":true,"dialog_turn_counter":1,"branch_exited_reason":"completed"}}'
[ERROR] [xxx.swift:50 decode(string:)] Context.decode: Failed 'typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: "Expected to decode Dictionary<String, Any> but found an array instead.", underlyingError: nil))

We are using:
Swift-sdk: 0.30.0
Kitura: 2.4.1

We have tried with both 4.1.1 and 4.1.2 of Swift with the same result .

**Comment by mkistler** [comment]
You don't have to decode the context value yourself -- the SDK already decodes it for you.  All the "dynamic" properties are be contained in the `additionalProperties` dictionary of the context object.

**Comment by vrisch** [comment]
Not sure I follow. Since this a web app (Kitura) we assumed we needed to attach the context to the web session, so that a user can continue their conversation separate from other users. The encode/decode are part of session restoration. Thanks for responding! We will continue investigating.

**Comment by mkistler** [comment]
Closing as there should be no need to encode/decode the Context when using the SDK.  Please open a new issue if there is some other problem here that needs to be addressed.
