### ISSUE TITLE
Watson - Error Domain=com.ibm.watson.developer-cloud.TextToSpeechV1

### ISSUE THREAD

**Issue by kasokuta** [watson-developer-cloud/swift-sdk#877]
If anyone knows what I am doing wrong feel free to post an answer.

So I am using watson from IBM and I want to use the Text To Speech funtion.

I am testing this on a simulator

I am using this code:
```

let textToSpeech = TextToSpeech(username: Credentials.TextToSpeechUsername, password: Credentials.TextToSpeechPassword)
    textToSpeech.serviceURL = Credentials.TextToSpeechUrl
    // The AVAudioPlayer object will stop playing if it falls out-of-scope.
    // Therefore, to prevent it from falling out-of-scope we declare it as
    // a property outside the completion handler where it will be played.
    var audioPlayer = AVAudioPlayer()

    let text = "hello john"
    let accept = "audio/wav"
    let voice = "en-US_LisaVoice"
    let failure = { (error: Error) in print(error) }
    textToSpeech.synthesize(text: text, accept: accept, voice: voice, failure: failure) { data in
        audioPlayer = try! AVAudioPlayer(data: data)
        audioPlayer.prepareToPlay()
        audioPlayer.play()
    }

```

The credencials and the Url are correct.

The error I get is:

`Error Domain=com.ibm.watson.developer-cloud.TextToSpeechV1 Code=403 "Forbidden" UserInfo={NSLocalizedDescription=Forbidden}
`

this is my .plist

![screen shot 2018-08-10 at 12 49 25](https://user-images.githubusercontent.com/11409645/43956388-e9f2d832-9c9b-11e8-97d8-c437b88af7db.png)

I post this problem on stackOverflow so I you want to answer me there its ok.

[https://stackoverflow.com/questions/51783848/watson-error-domain-com-ibm-watson-developer-cloud-texttospeechv1](url)

**Comment by mkistler** [comment]
The `403 Forbidden` error comes from the service, and basically means that your credentials are incorrect. Try issuing the same command with Curl using these credentials. That should confirm that your credentials are incorrect. If you can demonstrate that your credentials work with Curl but not with the Swift SDK, please reopen this issue.
