### ISSUE TITLE
How to set base_model_version for SpeechToTextSession class

### ISSUE THREAD

**Issue by hieultse03355** [watson-developer-cloud/swift-sdk#920]
Hi,
I'm trying to set up for SpeechToTextSession class, everything go fine such as i could set model, customizationID, acousticCustomizationID and learningOptOut in its contructor but i could not find for base_model_version property to set it up. 

- This is contructor of SpeechToTextSession:
![screen shot 2018-11-20 at 16 53 03](https://user-images.githubusercontent.com/14196282/48765463-c664e600-ece4-11e8-919c-2466e1d16eb1.png)

In SpeechToText class, i could recognize audio with full of settings even set up for Base_model_version for its queryParameters

- This is recognize funtion in SpeechToText class:
![screen shot 2018-11-20 at 17 07 45](https://user-images.githubusercontent.com/14196282/48766437-12b12580-ece7-11e8-9a4d-fd3fd9bbd950.png)

----> So How can i set Base_model_version property for SpeechToTextSession class?

**Comment by AnthonyOliveri** [comment]
@mkistler Do you know why SpeechToTextSession doesn't support the same parameters that SpeechToText does?

**Comment by mkistler** [comment]
SpeechToTextSession is hand-written, so parameters could have been missed during development, or the parameter was added later and the session code wasn't updated accordingly.

**Comment by AnthonyOliveri** [comment]
I confirmed that we are missing a few parameters from `SpeechToTextSession`, as shown in the [API docs](https://console.test.cloud.ibm.com/apidocs/speech-to-text#recognize-audio-websockets-). It's missing `language_customization_id`, `base_model_version`, and `metadata `. I'll have those added in the next release.

**Comment by mkistler** [comment]
Fixed in [Release 1.0](https://github.com/watson-developer-cloud/swift-sdk/releases/tag/1.0.0)
