### ISSUE TITLE
No way to put the custom grammer name

### ISSUE THREAD

**Issue by donpironet** [watson-developer-cloud/swift-sdk#938]
We have a custom grammer name how can I set this in swift?

**Comment by vincentbouillart** [comment]
+1

**Comment by AnthonyOliveri** [comment]
Could you provide more context? What you're trying to accomplish, what you've tried so far, etc.

**Comment by AnthonyOliveri** [comment]
Thanks for the clarification. You're right that the Swift SDK doesn't support custom grammars yet. Luckily, I'm already in the process of adding support for that in the recognize methods (recognize, recognizeUsingWebsocket, and recognizeMicrophone). I'll release a new version with that functionality by the end of the week.

**Comment by donpironet** [comment]
Awesome :-). Looking forward to it.

**Comment by donpironet** [comment]
I saw you updated the library so updated my versions as well. Now I have the possibility to add this parameter but when I do a request I get this in the warnings array:

"Unknown URL query params: grammar_name. Websockets requests should have the parameters in WS messages, not in URL."

And so the grammar name is not added.

Is it possible to fix this as quick as possible? Because we have an important demo and we really need this. Thank ahead!

**Comment by vincentbouillart** [comment]
> I saw you updated the library so updated my versions as well. Now I have the possibility to add this parameter but when I do a request I get this in the warnings array:
> 
> "Unknown URL query params: grammar_name. Websockets requests should have the parameters in WS messages, not in URL."
> 
> And so the grammar name is not added.
> 
> Is it possible to fix this as quick as possible? Because we have an important demo and we really need this. Thank ahead!

I have the same issue

**Comment by AnthonyOliveri** [comment]
Wow, that's no good. Thanks for letting me know. This is for `recognizeMicrophone`, right?

**Comment by donpironet** [comment]
Yes like this:

`recognizeMicrophone(settings: self.recognitionSettings, languageCustomizationID: self.viewModel.languageCustomizationId, grammarName: self.viewModel.grammarName)`

**Comment by AnthonyOliveri** [comment]
The API changed a bit with this release. You will need to remove the `grammarName` parameter from the `recognizeMicrophone` method. Also, do `self.recognitionSettings.grammarName = self.viewModel.grammarName` before calling `recognizeMicrophone`.

Let me know if that works for you.

**Comment by donpironet** [comment]
Thank you for fixing this so fast.  It works now :-).
