### ISSUE TITLE
How do I change language for RecognitionSettings structure?

### ISSUE THREAD

**Issue by Vincent-Loi** [watson-developer-cloud/swift-sdk#948]
Hi,

Just testing the example but couldn't find a way to change the language model? For example, to zh-CN?

Thanks,
Vince

**Comment by Vincent-Loi** [comment]
Managed to get it working and all good. But Chinese model doesn't seems to be returning any results at all? Any ideas?

`self.speechToText.recognizeMicrophone(settings: settings, model: "zh-CN_NarrowbandModel", completionHandler: { [weak self] response, error in })`

**Comment by germanattanasio** [comment]
Hi @Vincent-Loi, Do you have some code that we can use to this?

**Comment by TerenzeY** [comment]
Hi @germanattanasio, code below but technically if we set the model to these it returns results. 
- en-US_BroadbandModel
- fr-FR_BroadbandModel

But not these 
- zh-CN_NarrowbandModel
- en-GB_BroadbandModel

Anything we have missed?

Code is as simple as this:
`

    var speechToText: SpeechToText!
    var accumulator: SpeechRecognitionResultsAccumulator!
accumulator = SpeechRecognitionResultsAccumulator()
        speechToText = SpeechToText(apiKey: WatsonCredentials.apiKey)
        speechToText.serviceURL = "https://gateway-lon.watsonplatform.net/speech-to-text/api"
var settings = RecognitionSettings(contentType: "audio/ogg;codecs=opus")
                settings.timestamps = true
                settings.speakerLabels = true
                settings.interimResults = true
                settings.smartFormatting = true
                self.speechToText.recognizeMicrophone(settings: settings, model: "en-GB_BroadbandModel", completionHandler: { [weak self] response, error in
                    guard let results = response?.result else { return }
                    self?.accumulator.add(results: results)
                    let transcript = self?.accumulator.bestTranscript
                    self?.textView.text = transcript
                })

`

**Comment by TerenzeY** [comment]
Quick update – actually found the problem. Removing the following line works:
                settings.smartFormatting = true

**Comment by germanattanasio** [comment]
Cool. I'm going close this then.
