### ISSUE TITLE
[speech-to-text] SpeechToTextSession work with apiKey, not with username and password

### ISSUE THREAD

**Issue by maggix** [watson-developer-cloud/swift-sdk#950]
**Overview**
When initializing a `SpeechToTextSession` using `username` and `password` as parameter, the text speech to text recognition does not work, using `apiKey` as `username` and the API Key as password.

It *does* however work when using:

```
        session = SpeechToTextSession(
            apiKey: "<the api key>"
        )
```

**Expected behavior**
The behavior of using username and password, setting the username to be the string `"apiKey"` should provide the same behavior as initializing the `SpeechToTextSession` using the `apiKey` parameter.

**Actual behavior**
In practice, initializing the `SpeechToTextSession` using username and password does not work. It works in other APIs, such as the standalone `SpeechToText`. 

**How to reproduce**
Please see my repo: https://github.com/maggix/speech-to-text-swift 

**Screenshots**
N/A
**SDK Version**
Happened in 1.1.0, still replicating in 1.4.0

**Additional information:**
- OS: tested on iOS 12
- Swift 4

**Additional context**
N/A

**Comment by germanattanasio** [comment]
@maggix Speech to Text sessions are deprecated. Feel free to remove the methods and send us a PR

**Comment by repjarms** [comment]
@maggix @germanattanasio I see a PR associated with this issue. Was this resolve, and can it be closed?
