### ISSUE TITLE
Goals/plans for Release 2.0

### ISSUE THREAD

**Issue by mkistler** [watson-developer-cloud/swift-sdk#952]
The following is a proposed set of changes for Release 2.0 of the Watson Swift SDK, broken into `breaking` and `non-breaking` changes:

### Breaking changes

- [x] Migrate to new OpenAPI 3.0 generator, which will change the order of parameters for some methods
- [x] Breaking changes in class/property names resulting from changes in the API definitions
- [x] Parameters passed as `URL` in the previous release will be changed to `Data`, with an associated `filename` parameter where appropriate
- [x] All init methods to accept `version` as first parameter
- [x] The init method to extract credentials from a file will be dropped from iOS, and in Linux the method will only use the file `ibm-credentials.env` -- not an arbitrary URL

### Non-breaking changes

**Comment by germanattanasio** [comment]
> Mike: Migrate to new OpenAPI 3.0 generator, which will change the order of parameters for some methods 
 
German: @mkistler does it make sense to switch to a builder pattern for requests? that way you won't have breaking changes every time the parameters order changes.

**Comment by mkistler** [comment]
Builders are not really necessary in Swift since parameters with default values can be omitted -- unlike Java. And builders are not a common pattern in Swift, so I think it could hinder developer adoption to introduce this pattern.

**Comment by germanattanasio** [comment]
Those are really good points @mkistler!

**Comment by mkistler** [comment]
Release 2.0 is out!

https://github.com/watson-developer-cloud/swift-sdk/releases/tag/2.0.0
