### ISSUE TITLE
Add support for Swift 5

### ISSUE THREAD

**Issue by donpironet** [watson-developer-cloud/swift-sdk#970]
Is it possible to add Swift 5 support? When now building with Carthage I get this error:

```
***  Skipped installing swift-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)."
```

Even when I run carthage with --no-use-binaries the project compiles but I can't use the recognizeMicrophone method. It doesn't compile in Swift 5.

**Comment by mkistler** [comment]
I just built the Swift SDK with Swift 5 without any errors.

Can you please post the compile errors you are seeing?

**Comment by donpironet** [comment]
I'm using carthage to get the framework I have this in my cartfile:

`github "watson-developer-cloud/swift-sdk"`

```
carthage update --platform iOS
*** Fetching swift-sdk
*** Fetching Starscream
*** Fetching restkit
*** Checking out restkit at "3.0.1"
*** Checking out Starscream at "3.0.5"
*** Checking out swift-sdk at "2.0.3"
*** xcodebuild output can be found in /var/folders/3g/s0qk43z17rlg0rphzt3ptkdc0000gn/T/carthage-xcodebuild.Cn2YhX.log
*** Downloading swift-sdk.framework binary at "2.0.3"
***  Skipped installing swift-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)."
```

**Comment by donpironet** [comment]
@mkistler any update on this?

**Comment by mkistler** [comment]
Sorry ... are you saying that the build stopped there? Did it not compile the Swift SDK?

**Comment by mkistler** [comment]
Here's why I see for the configuration you describe:
```
[mkistler@mkistlers-MBP] ~/tmp>mkdir don
[mkistler@mkistlers-MBP] ~/tmp>cd don
[mkistler@mkistlers-MBP] ~/tmp/don>vi Cartfile
[mkistler@mkistlers-MBP] ~/tmp/don>carthage update --platform iOS
*** Fetching swift-sdk
*** Fetching restkit
*** Fetching Starscream
*** Checking out Starscream at "3.0.5"
*** Checking out restkit at "3.0.2"
*** Checking out swift-sdk at "2.0.3"
*** xcodebuild output can be found in /var/folders/ck/_z7lh_n91pn4pdr09b1jtmqw0000gn/T/carthage-xcodebuild.W2qdea.log
*** Downloading swift-sdk.framework binary at "2.0.3"
***  Skipped installing swift-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)."

    Falling back to building from the source
*** Building scheme "RestKit" in RestKit.xcodeproj
*** Building scheme "Starscream" in Starscream.xcodeproj
*** Building scheme "CompareComplyV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "AssistantV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "DiscoveryV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "AssistantV2" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "NaturalLanguageClassifierV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "LanguageTranslatorV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "NaturalLanguageUnderstandingV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "PersonalityInsightsV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "VisualRecognitionV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "TextToSpeechV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "ToneAnalyzerV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "SpeechToTextV1" in WatsonDeveloperCloud.xcodeproj
[mkistler@mkistlers-MBP] ~/tmp/don>
```

SDK is installed and built successfully.

Does it work differently for you?

**Comment by donpironet** [comment]
No it's the same but when I compile the project then I get errors on the requestMicrophone method because the ResultType is changed in Swift 5.

**Comment by mkistler** [comment]
According to the [Carthage documentation](https://github.com/Carthage/Carthage):
> Carthage uses the output of xcrun swift --version to determine the local Swift version,

For me:
```
[mkistler@mkistlers-MBP] ~>xcrun swift --version
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.6.0
[mkistler@mkistlers-MBP] ~>
```

So the build output I show above used Swift 5, and as you can see, the SpeechToTextV1 target compiled with no errors. So if you are getting compile errors building SpeechToTextV1 with Swift 5, please post them.

**Comment by donpironet** [comment]
@mkistler I have the same swift version like you can see on the screenshots. In your logs above you also notice that it doesn't built successfully because of this in your log files (I have the same problem):

> ***  Skipped installing swift-sdk.framework binary due to the error:
> 	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)."
> 
>     Falling back to building from the source

It's not a big problem if then the code would compile but like you can see on the screenshot it doesn't because you need to update the code probably to work with swift 5.

<img width="1440" alt="Screenshot 2019-06-13 at 11 36 45" src="https://user-images.githubusercontent.com/6583650/59422406-9e4bea00-8dd0-11e9-86c4-663118cd5e3f.png">
<img width="1552" alt="Screenshot 2019-06-13 at 11 42 36" src="https://user-images.githubusercontent.com/6583650/59422421-a572f800-8dd0-11e9-8bc3-2d2a90b9e140.png">

**Comment by mkistler** [comment]
Okay ... that last screen shot explains the situation.  The problem is _not_ that the SDK fails to compile or work with Swift 5. The problem is that the interface to `recognizeMicrophone` changed in the latest major release -- it no longer takes a `completionHandler`, but instead takes a `RecognizeCallback` object, which has references to `onResult` and `onError` handlers -- and you have not updated your code (`toggleWatson`) to the new interface.

You can see an example of the new interface and how to create and pass the `RecognizeCallback` object [in the SDK Tests](https://github.com/watson-developer-cloud/swift-sdk/blob/master/Tests/SpeechToTextV1Tests/SpeechToTextRecognizeTests.swift#L229).

**Comment by donpironet** [comment]
Thank you. I was confused because of the new ResultType in Swift 5 and when I clicked through I didn't see this. Works now only the warning is still there that it's still Swift 4.
