### ISSUE TITLE
Goals/plans for Release 3.0

### ISSUE THREAD

**Issue by mkistler** [watson-developer-cloud/swift-sdk#975]
We are starting the planning phase for the next major release of the Watson Swift SDK, Release 3.0, expected to be released later this year.

This issue will be used to track features and changes we want to make in the next major release. We welcome community feedback on these goals - do people want these things? Are there other implementations/packages we should be looking at? Any comments are appreciated!

## Planned changes
- [ ] Provide more flexible and extensible support for authorization. This may include allowing the application to specify headers to be passed on token requests, and whether token requests can use insecure connections (e.g. self-signed certificaties). This might be a breaking change for some applications.
- [ ] Changes to the SDK Swift Package to enable the new Swift Package manager features in Xcode 11.
- [ ] Add support for the websockets interface in the Text to Speech service.

**Comment by repjarms** [comment]
As we discussed, I think having Swift 5 support would be ideal to include in 3.0.

**Comment by ianpartridge** [comment]
Depending your timeline you should probably shoot for 5.1 as well.

**Comment by repjarms** [comment]
@ianpartridge yes we plan to test the release with the 5.1 dev image for Swift. good suggestion.
