### ISSUE TITLE
Write Kitura Examples using the SDK

### ISSUE THREAD

**Issue by repjarms** [watson-developer-cloud/swift-sdk#982]
### When you open an issue for a feature request, please add as much detail as possible:

Since the SDK is available on Linux, it would be nice to include code samples that show how Watson SDK methods can be integrated in endpoints through an HTTP library such as Kitura. If such examples already exist, we could feature them more prominently in our related repos.

CC @ianpartridge

**Comment by ianpartridge** [comment]
Sounds like a great idea!
