### ISSUE TITLE
[visual-recognition] Need to remove `detectFaces()` from SDK

### ISSUE THREAD

**Issue by DevWithTheHair** [watson-developer-cloud/swift-sdk#990]
Per the `12 September 2019` [Release Notes](https://cloud.ibm.com/docs/services/visual-recognition?topic=visual-recognition-release-notes#12-september-2019):

> **Detect faces methods removed**
> 
> As of 12 September 2019, the **Detect Faces** methods are removed from Visual Recognition. These methods include `GET /v3/detect_faces` and `POST /v3/detect_faces`.

As a result of this change to the Watson Visual Recognition API, the SDK's `detectFaces()` method returns an empty response in all cases. Removing the method and its associated test cases will reduce confusion for users of the SDK.

**Comment by repjarms** [comment]
@DevWithTheHair thank you for filing this issue! We are in the process of preparing a new major release for the SDK which should be available next week which removes the face detection method going forward.

I will also look into publishing a patch release to the `2.X` release branch which throws a formatted error informing people that the method has been removed.

**Comment by DevWithTheHair** [comment]
@repjarms that's good to know! Thank you for responding. Publishing a patch release to the `2.x` branch would indeed be excellent.

The primary reason I noticed this situation is that one of my IBM Cloud Functions projects _mysteriously_ stopped working (or so it seemed). It took me a while (😅) to figure out that the problem wasn't my code per se but rather that the functionality had been removed from the underlying API. Thankfully I was able to read the Release Notes (and Watson Swift SDK source code) and figured out the problem.

**Comment by DevWithTheHair** [comment]
@repjarms BTW, is there someplace I should be looking at for the _reason_ why this particular API was removed?

The Release Notes do a good job of describing the _what_ was done (i.e. removed the endpoint) but not much with regard to the _why_ it was done.

Just curious as to whether I should be following some additional resource for that particular information.
