### ISSUE TITLE
Issues after updating to latest iOS SDK with WatsonAuthenticator

### ISSUE THREAD

**Issue by shokaveli** [watson-developer-cloud/swift-sdk#999]
After updating to the following :

    pod 'IBMWatsonAssistantV1', '~> 3.0.0'
    pod 'IBMWatsonConversationV1', '~> 0.38.1'
    pod 'IBMWatsonTextToSpeechV1', '~> 3.0.0'

I know am seeing an issue with the new WatsonAuthenticator. I'm getting a "does not conform to protocol 'Authenticator'" in the class in which I am trying to init a TextToSpeech object like so :

    var textToSpeech = TextToSpeech.init(authenticator: self)

I am clearly conforming to the protocol : 

    func authenticate(request: RestRequest, completionHandler: @escaping (RestRequest?, RestError?) -> Void) {}

    func authenticate(request: URLRequest, completionHandler: @escaping (URLRequest?, RestError?) -> Void) {}

Yet I cant get past this error and build.  Please any help would be appreciated.  I am using Swift 5.

[![Error][1]][1]

  [1]: https://i.stack.imgur.com/tBxbe.png

**Comment by repjarms** [comment]
@shokaveli thanks for bringing this up, and apologies for the initial delay in getting to this. Let me see if I can replicate this and I'll write back and see if I can help here.

**Comment by shokaveli** [comment]
Great thanks!

**Comment by repjarms** [comment]
@shokaveli I believe I've found a possible cause the issue here. By implementing the protocol `Authenticator`, you need to provide two methods that use `RestRequest` and `RestError`. This requires you to explicitly import the `IBMSwiftSDKCore`, which is a sub-dependency of the SDK pods.

We `typealias` `RestError` into `WatsonError`, but we do not have a `typealias` for `RestRequest`, so that import is needed for it to compile.

```swift
import TextToSpeech
import IBMSwiftSDKCore

class Something: NSObject, WatsonAuthenticator {
    func authenticate(request: RestRequest, completionHandler: @escaping (RestRequest?, RestError?) -> Void) {
        
    }
    
    func authenticate(request: URLRequest, completionHandler: @escaping (URLRequest?, RestError?) -> Void) {
        
    }
    
    
}
```

**Comment by shokaveli** [comment]
That fixed it! Thanks!

**Comment by repjarms** [comment]
@shokaveli great! Glad that was it. Closing this as resolved
